# Form implementation generated from reading ui file 'ui/category_add.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_hopThoaiMacDinh(object):
    def setupUi(self, hopThoaiMacDinh):
        hopThoaiMacDinh.setObjectName("hopThoaiMacDinh")
        hopThoaiMacDinh.resize(382, 329)
        self.verticalLayout = QtWidgets.QVBoxLayout(hopThoaiMacDinh)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.labelID = QtWidgets.QLabel(parent=hopThoaiMacDinh)
        self.labelID.setObjectName("labelID")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.labelID)
        self.txtMaSP = QtWidgets.QLineEdit(parent=hopThoaiMacDinh)
        self.txtMaSP.setReadOnly(True)
        self.txtMaSP.setObjectName("txtMaSP")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.txtMaSP)
        self.labelName = QtWidgets.QLabel(parent=hopThoaiMacDinh)
        self.labelName.setObjectName("labelName")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.labelName)
        self.txtTenDM = QtWidgets.QLineEdit(parent=hopThoaiMacDinh)
        self.txtTenDM.setReadOnly(True)
        self.txtTenDM.setObjectName("txtTenDM")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.txtTenDM)
        self.verticalLayout.addLayout(self.formLayout)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.labelCategory = QtWidgets.QLabel(parent=hopThoaiMacDinh)
        self.labelCategory.setObjectName("labelCategory")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.labelCategory)
        self.txtMoTaSP = QtWidgets.QTextEdit(parent=hopThoaiMacDinh)
        self.txtMoTaSP.setReadOnly(True)
        self.txtMoTaSP.setObjectName("txtMoTaSP")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.txtMoTaSP)
        self.verticalLayout.addLayout(self.formLayout_2)
        self.hboxlayout = QtWidgets.QHBoxLayout()
        self.hboxlayout.setObjectName("hboxlayout")
        spacerItem = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.hboxlayout.addItem(spacerItem)
        self.btnLuu = QtWidgets.QPushButton(parent=hopThoaiMacDinh)
        self.btnLuu.setObjectName("btnLuu")
        self.hboxlayout.addWidget(self.btnLuu)
        self.btnHuy = QtWidgets.QPushButton(parent=hopThoaiMacDinh)
        self.btnHuy.setObjectName("btnHuy")
        self.hboxlayout.addWidget(self.btnHuy)
        self.verticalLayout.addLayout(self.hboxlayout)

        self.retranslateUi(hopThoaiMacDinh)
        QtCore.QMetaObject.connectSlotsByName(hopThoaiMacDinh)

    def retranslateUi(self, hopThoaiMacDinh):
        _translate = QtCore.QCoreApplication.translate
        hopThoaiMacDinh.setWindowTitle(_translate("hopThoaiMacDinh", "Dialog"))
        self.labelID.setText(_translate("hopThoaiMacDinh", "Mã Danh Mục"))
        self.labelName.setText(_translate("hopThoaiMacDinh", "Tên Danh Mục"))
        self.labelCategory.setText(_translate("hopThoaiMacDinh", "Mô Tả"))
        self.btnLuu.setText(_translate("hopThoaiMacDinh", "Lưu"))
        self.btnHuy.setText(_translate("hopThoaiMacDinh", "Hủy"))


class CategoryAddDialog(QtWidgets.QDialog, Ui_hopThoaiMacDinh):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.setupUi(self)
        self.category = None
        self.btnLuu.clicked.connect(self.on_save)
        self.btnHuy.clicked.connect(self.reject)

    def prepare_for_add(self):
        self.category = None
        self.txtMaSP.setReadOnly(True)
        self.txtTenDM.setReadOnly(False)
        self.txtMoTaSP.setReadOnly(False)
        if hasattr(self.parent(), "generate_category_code"):
            self.txtMaSP.setText(self.parent().generate_category_code())
        else:
            self.txtMaSP.setText("")
        self.txtTenDM.clear()
        self.txtMoTaSP.clear()

    def prepare_for_update(self, category):
        self.category = category
        self.txtMaSP.setText(category.get("maDM", ""))
        self.txtMaSP.setReadOnly(True)
        self.txtTenDM.setReadOnly(False)
        self.txtMoTaSP.setReadOnly(False)
        self.txtTenDM.setText(category.get("tenDM", ""))
        self.txtMoTaSP.setPlainText(category.get("moTa", ""))

    def get_data(self):
        return {
            "maDM": self.txtMaSP.text().strip(),
            "tenDM": self.txtTenDM.text().strip(),
            "moTa": self.txtMoTaSP.toPlainText().strip(),
            "sl": self.category.get("sl", 0) if self.category else 0,
        }

    def on_save(self):
        if not self.txtTenDM.text().strip():
            QtWidgets.QMessageBox.warning(self, "Thiếu thông tin", "Vui lòng nhập tên danh mục.")
            return
        self.accept()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    hopThoaiMacDinh = QtWidgets.QDialog()
    ui = Ui_hopThoaiMacDinh()
    ui.setupUi(hopThoaiMacDinh)
    hopThoaiMacDinh.show()
    sys.exit(app.exec())
