# Form implementation generated from reading ui file 'ui/category_detail.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_hopThoaiDanhMucChiTiet(object):
    def setupUi(self, hopThoaiDanhMucChiTiet):
        hopThoaiDanhMucChiTiet.setObjectName("hopThoaiDanhMucChiTiet")
        hopThoaiDanhMucChiTiet.resize(811, 665)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(hopThoaiDanhMucChiTiet)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.nhomMacDinh = QtWidgets.QGroupBox(parent=hopThoaiDanhMucChiTiet)
        self.nhomMacDinh.setObjectName("nhomMacDinh")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.nhomMacDinh)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setObjectName("formLayout_4")
        self.labelID = QtWidgets.QLabel(parent=self.nhomMacDinh)
        self.labelID.setObjectName("labelID")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.labelID)
        self.txtMaDM = QtWidgets.QLineEdit(parent=self.nhomMacDinh)
        self.txtMaDM.setReadOnly(True)
        self.txtMaDM.setObjectName("txtMaDM")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.txtMaDM)
        self.verticalLayout_2.addLayout(self.formLayout_4)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.labelName = QtWidgets.QLabel(parent=self.nhomMacDinh)
        self.labelName.setObjectName("labelName")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.labelName)
        self.txtTenDM = QtWidgets.QLineEdit(parent=self.nhomMacDinh)
        self.txtTenDM.setObjectName("txtTenDM")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.txtTenDM)
        self.verticalLayout_2.addLayout(self.formLayout_3)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.labelDescription = QtWidgets.QLabel(parent=self.nhomMacDinh)
        self.labelDescription.setObjectName("labelDescription")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.labelDescription)
        self.txtMoTaDM = QtWidgets.QTextEdit(parent=self.nhomMacDinh)
        self.txtMoTaDM.setMinimumSize(QtCore.QSize(0, 120))
        self.txtMoTaDM.setObjectName("txtMoTaDM")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.txtMoTaDM)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.verticalLayout_3.addWidget(self.nhomMacDinh)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.buttonLayout.addItem(spacerItem)
        self.btnCapNhatDM = QtWidgets.QPushButton(parent=hopThoaiDanhMucChiTiet)
        self.btnCapNhatDM.setMinimumSize(QtCore.QSize(100, 35))
        self.btnCapNhatDM.setObjectName("btnCapNhatDM")
        self.buttonLayout.addWidget(self.btnCapNhatDM)
        self.btnXoaDM = QtWidgets.QPushButton(parent=hopThoaiDanhMucChiTiet)
        self.btnXoaDM.setMinimumSize(QtCore.QSize(100, 35))
        self.btnXoaDM.setObjectName("btnXoaDM")
        self.buttonLayout.addWidget(self.btnXoaDM)
        self.verticalLayout_3.addLayout(self.buttonLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=hopThoaiDanhMucChiTiet)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.tblDanhSachSP = QtWidgets.QTableWidget(parent=hopThoaiDanhMucChiTiet)
        self.tblDanhSachSP.setObjectName("tblDanhSachSP")
        self.tblDanhSachSP.setColumnCount(5)
        self.tblDanhSachSP.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblDanhSachSP.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblDanhSachSP.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblDanhSachSP.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblDanhSachSP.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblDanhSachSP.setHorizontalHeaderItem(4, item)
        self.verticalLayout.addWidget(self.tblDanhSachSP)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_3.setStretch(0, 4)
        self.verticalLayout_3.setStretch(1, 2)
        self.verticalLayout_3.setStretch(2, 1)
        self.verticalLayout_3.setStretch(3, 56)

        self.retranslateUi(hopThoaiDanhMucChiTiet)
        QtCore.QMetaObject.connectSlotsByName(hopThoaiDanhMucChiTiet)

    def retranslateUi(self, hopThoaiDanhMucChiTiet):
        _translate = QtCore.QCoreApplication.translate
        hopThoaiDanhMucChiTiet.setWindowTitle(_translate("hopThoaiDanhMucChiTiet", "Category Detail"))
        self.nhomMacDinh.setTitle(_translate("hopThoaiDanhMucChiTiet", "Thông tin Danh Mục"))
        self.labelID.setText(_translate("hopThoaiDanhMucChiTiet", "Mã Danh Mục"))
        self.labelName.setText(_translate("hopThoaiDanhMucChiTiet", "Tên Danh Mục"))
        self.labelDescription.setText(_translate("hopThoaiDanhMucChiTiet", "Mô tả"))
        self.btnCapNhatDM.setText(_translate("hopThoaiDanhMucChiTiet", "Cập Nhật"))
        self.btnXoaDM.setText(_translate("hopThoaiDanhMucChiTiet", "Xóa Danh Mục"))
        self.label.setText(_translate("hopThoaiDanhMucChiTiet", "Danh sách sản phẩm"))
        item = self.tblDanhSachSP.horizontalHeaderItem(0)
        item.setText(_translate("hopThoaiDanhMucChiTiet", "Mã SP"))
        item = self.tblDanhSachSP.horizontalHeaderItem(1)
        item.setText(_translate("hopThoaiDanhMucChiTiet", "Tên SP"))
        item = self.tblDanhSachSP.horizontalHeaderItem(2)
        item.setText(_translate("hopThoaiDanhMucChiTiet", "Giá"))
        item = self.tblDanhSachSP.horizontalHeaderItem(3)
        item.setText(_translate("hopThoaiDanhMucChiTiet", "Tồn Kho"))
        item = self.tblDanhSachSP.horizontalHeaderItem(4)
        item.setText(_translate("hopThoaiDanhMucChiTiet", "Trạng Thái"))


class CategoryDetailDialog(QtWidgets.QDialog, Ui_hopThoaiDanhMucChiTiet):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.setupUi(self)
        self.category = None
        self.btnCapNhatDM.clicked.connect(self.on_update)
        self.btnXoaDM.clicked.connect(self.on_delete)

    def fill_category(self, category, products):
        self.category = category
        self.txtMaDM.setReadOnly(True)
        self.txtTenDM.setReadOnly(True)
        self.txtMoTaDM.setReadOnly(True)
        self.txtMaDM.setText(category.get("maDM", ""))
        self.txtTenDM.setText(category.get("tenDM", ""))
        self.txtMoTaDM.setPlainText(category.get("moTa", ""))
        self.tblDanhSachSP.setRowCount(0)
        for product in products:
            row = self.tblDanhSachSP.rowCount()
            self.tblDanhSachSP.insertRow(row)
            self.tblDanhSachSP.setItem(row, 0, QtWidgets.QTableWidgetItem(product.get("maSP", "")))
            self.tblDanhSachSP.setItem(row, 1, QtWidgets.QTableWidgetItem(product.get("tenSP", "")))
            self.tblDanhSachSP.setItem(row, 2, QtWidgets.QTableWidgetItem(product.get("gia", "")))
            self.tblDanhSachSP.setItem(row, 3, QtWidgets.QTableWidgetItem(product.get("tonKho", "")))
            self.tblDanhSachSP.setItem(row, 4, QtWidgets.QTableWidgetItem(product.get("trangThai", "")))

    def on_update(self):
        if self.parent() is not None and hasattr(self.parent(), "open_update_category"):
            self.parent().open_update_category(self.category)
        self.accept()

    def on_delete(self):
        if self.parent() is not None and hasattr(self.parent(), "delete_category"):
            self.parent().delete_category(self.category)
        self.accept()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    hopThoaiDanhMucChiTiet = QtWidgets.QDialog()
    ui = Ui_hopThoaiDanhMucChiTiet()
    ui.setupUi(hopThoaiDanhMucChiTiet)
    hopThoaiDanhMucChiTiet.show()
    sys.exit(app.exec())
