# Form implementation generated from reading ui file 'ui/category_add.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtWidgets
from .category_add_ui import Ui_hopThoaiMacDinh


class CategoryAddDialog(QtWidgets.QDialog, Ui_hopThoaiMacDinh):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.setupUi(self)
        self.category = None
        self.btnLuu.clicked.connect(self.on_save)
        self.btnHuy.clicked.connect(self.reject)

    def prepare_for_add(self):
        self.category = None
        self.txtMaSP.setReadOnly(True)
        self.txtTenDM.setReadOnly(False)
        self.txtMoTaSP.setReadOnly(False)
        if hasattr(self.parent(), "generate_category_code"):
            self.txtMaSP.setText(self.parent().generate_category_code())
        else:
            self.txtMaSP.setText("")
        self.txtTenDM.clear()
        self.txtMoTaSP.clear()

    def prepare_for_update(self, category):
        self.category = category
        self.txtMaSP.setText(category.get("maDM", ""))
        self.txtMaSP.setReadOnly(True)
        self.txtTenDM.setReadOnly(False)
        self.txtMoTaSP.setReadOnly(False)
        self.txtTenDM.setText(category.get("tenDM", ""))
        self.txtMoTaSP.setPlainText(category.get("moTa", ""))

    def get_data(self):
        return {
            "maDM": self.txtMaSP.text().strip(),
            "tenDM": self.txtTenDM.text().strip(),
            "moTa": self.txtMoTaSP.toPlainText().strip(),
            "sl": self.category.get("sl", 0) if self.category else 0,
        }

    def on_save(self):
        if not self.txtTenDM.text().strip():
            QtWidgets.QMessageBox.warning(self, "Thiếu thông tin", "Vui lòng nhập tên danh mục.")
            return
        self.accept()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dlg = CategoryAddDialog()
    dlg.show()
    sys.exit(app.exec())
