# Form implementation generated from reading ui file 'ui/category_detail.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtWidgets
from .category_detail_ui import Ui_hopThoaiDanhMucChiTiet


class CategoryDetailDialog(QtWidgets.QDialog, Ui_hopThoaiDanhMucChiTiet):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.setupUi(self)
        self.category = None
        self.btnCapNhatDM.clicked.connect(self.on_update)
        self.btnXoaDM.clicked.connect(self.on_delete)

    def fill_category(self, category, products):
        self.category = category
        self.txtMaDM.setReadOnly(True)
        self.txtTenDM.setReadOnly(True)
        self.txtMoTaDM.setReadOnly(True)
        self.txtMaDM.setText(category.get("maDM", ""))
        self.txtTenDM.setText(category.get("tenDM", ""))
        self.txtMoTaDM.setPlainText(category.get("moTa", ""))
        self.tblDanhSachSP.setRowCount(0)
        for product in products:
            row = self.tblDanhSachSP.rowCount()
            self.tblDanhSachSP.insertRow(row)
            self.tblDanhSachSP.setItem(row, 0, QtWidgets.QTableWidgetItem(product.get("maSP", "")))
            self.tblDanhSachSP.setItem(row, 1, QtWidgets.QTableWidgetItem(product.get("tenSP", "")))
            self.tblDanhSachSP.setItem(row, 2, QtWidgets.QTableWidgetItem(product.get("gia", "")))
            self.tblDanhSachSP.setItem(row, 3, QtWidgets.QTableWidgetItem(product.get("tonKho", "")))
            self.tblDanhSachSP.setItem(row, 4, QtWidgets.QTableWidgetItem(product.get("trangThai", "")))

    def on_update(self):
        if self.parent() is not None and hasattr(self.parent(), "open_update_category"):
            self.parent().open_update_category(self.category)
        self.accept()

    def on_delete(self):
        if self.parent() is not None and hasattr(self.parent(), "delete_category"):
            self.parent().delete_category(self.category)
        self.accept()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dlg = CategoryDetailDialog()
    dlg.show()
    sys.exit(app.exec())
