# Form implementation generated from reading ui file 'ui/login.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LoginDialog(object):
    def setupUi(self, LoginDialog):
        LoginDialog.setObjectName("LoginDialog")
        LoginDialog.resize(581, 346)
        font = QtGui.QFont()
        font.setPointSize(10)
        LoginDialog.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/Admin/Downloads/entrance.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        LoginDialog.setWindowIcon(icon)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("ui\\../resources/icons/entrance.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        LoginDialog.setWindowIcon(icon1)
        LoginDialog.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(LoginDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblTitle_7 = QtWidgets.QLabel(parent=LoginDialog)
        self.lblTitle_7.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblTitle_7.setObjectName("lblTitle_7")
        self.verticalLayout.addWidget(self.lblTitle_7)
        self.grpLogin = QtWidgets.QGroupBox(parent=LoginDialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.grpLogin.setFont(font)
        self.grpLogin.setObjectName("grpLogin")
        self.formLayout = QtWidgets.QFormLayout(self.grpLogin)
        self.formLayout.setObjectName("formLayout")
        self.lblUsername = QtWidgets.QLabel(parent=self.grpLogin)
        self.lblUsername.setObjectName("lblUsername")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblUsername)
        self.txtTenDangNhap = QtWidgets.QLineEdit(parent=self.grpLogin)
        self.txtTenDangNhap.setObjectName("txtTenDangNhap")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.txtTenDangNhap)
        self.lblPassword = QtWidgets.QLabel(parent=self.grpLogin)
        self.lblPassword.setObjectName("lblPassword")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblPassword)
        self.txtPMatKhau = QtWidgets.QLineEdit(parent=self.grpLogin)
        self.txtPMatKhau.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.txtPMatKhau.setObjectName("txtPMatKhau")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.txtPMatKhau)
        self.verticalLayout.addWidget(self.grpLogin)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btnDangNhap = QtWidgets.QPushButton(parent=LoginDialog)
        self.btnDangNhap.setMinimumSize(QtCore.QSize(90, 32))
        self.btnDangNhap.setObjectName("btnDangNhap")
        self.horizontalLayout.addWidget(self.btnDangNhap)
        self.btnThoatDangNhap = QtWidgets.QPushButton(parent=LoginDialog)
        self.btnThoatDangNhap.setMinimumSize(QtCore.QSize(90, 32))
        self.btnThoatDangNhap.setObjectName("btnThoatDangNhap")
        self.horizontalLayout.addWidget(self.btnThoatDangNhap)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(LoginDialog)
        QtCore.QMetaObject.connectSlotsByName(LoginDialog)

    def retranslateUi(self, LoginDialog):
        _translate = QtCore.QCoreApplication.translate
        LoginDialog.setWindowTitle(_translate("LoginDialog", "đăng nhập"))
        self.lblTitle_7.setStyleSheet(_translate("LoginDialog", "\n"
"font: 18pt \"Arial\";\n"
"font-weight:bold;\n"
"color:white;\n"
"background:#1976D2;\n"
"padding:15px;\n"
"border-radius:8px;\n"
"       "))
        self.lblTitle_7.setText(_translate("LoginDialog", "<html><head/><body><p><span style=\" font-size:14pt;\">HỆ THỐNG QUẢN LÝ CỬA HÀNG</span></p></body></html>"))
        self.grpLogin.setTitle(_translate("LoginDialog", "Thông tin đăng nhập"))
        self.lblUsername.setText(_translate("LoginDialog", "Tên đăng nhập"))
        self.lblPassword.setText(_translate("LoginDialog", "Mật khẩu"))
        self.btnDangNhap.setText(_translate("LoginDialog", "Đăng nhập"))
        self.btnThoatDangNhap.setText(_translate("LoginDialog", "Thoát"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LoginDialog = QtWidgets.QDialog()
    ui = Ui_LoginDialog()
    ui.setupUi(LoginDialog)
    LoginDialog.show()
    sys.exit(app.exec())
