# Form implementation generated from reading ui file 'ui/payment_detail.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtWidgets
from .payment_detail_ui import Ui_hopThoaiThanhToanChiTiet


class PaymentDetailDialog(QtWidgets.QDialog, Ui_hopThoaiThanhToanChiTiet):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.setupUi(self)
        self.payment = None
        self.btnXacNhanTT.clicked.connect(self.on_confirm)
        self.btnClose.clicked.connect(self.reject)

    def fill_payment(self, payment):
        self.payment = payment
        self.lblMaTT.setText(payment.get("maTT", ""))
        self.lblMaDH.setText(payment.get("maDH", ""))
        self.lblTenKH.setText(payment.get("khachHang", ""))
        self.lblPhuongThucThanhToan.setText(payment.get("phuongThuc", ""))
        self.lblngayTT.setText(payment.get("ngayTT", "") or "--/--/----")
        self.lblTrangThaiTT.setText(payment.get("trangThai", ""))
        self.lblTongTien.setText(f"{payment.get('tongTien', 0):,} VND")

    def on_confirm(self):
        if self.payment is None:
            return
        if self.parent() is not None and hasattr(self.parent(), "confirm_payment"):
            self.parent().confirm_payment(self.payment)
        self.accept()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dlg = PaymentDetailDialog()
    dlg.show()
    sys.exit(app.exec())
