from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_hopThoaiThanhToanChiTiet(object):
    def setupUi(self, hopThoaiThanhToanChiTiet):
        hopThoaiThanhToanChiTiet.setObjectName("hopThoaiThanhToanChiTiet")
        hopThoaiThanhToanChiTiet.resize(450, 550)
        self.mainVerticalLayout = QtWidgets.QVBoxLayout(hopThoaiThanhToanChiTiet)
        self.mainVerticalLayout.setObjectName("mainVerticalLayout")
        self.lblHeader = QtWidgets.QLabel(parent=hopThoaiThanhToanChiTiet)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lblHeader.setFont(font)
        self.lblHeader.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblHeader.setObjectName("lblHeader")
        self.mainVerticalLayout.addWidget(self.lblHeader)
        self.phanTuTop = QtWidgets.QFrame(parent=hopThoaiThanhToanChiTiet)
        self.phanTuTop.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.phanTuTop.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.phanTuTop.setObjectName("phanTuTop")
        self.mainVerticalLayout.addWidget(self.phanTuTop)
        self.nhomThongTin = QtWidgets.QGroupBox(parent=hopThoaiThanhToanChiTiet)
        self.nhomThongTin.setObjectName("nhomThongTin")
        self.formLayout = QtWidgets.QFormLayout(self.nhomThongTin)
        self.formLayout.setVerticalSpacing(12)
        self.formLayout.setObjectName("formLayout")
        self.lblTitlePayID = QtWidgets.QLabel(parent=self.nhomThongTin)
        self.lblTitlePayID.setObjectName("lblTitlePayID")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblTitlePayID)
        self.lblMaTT = QtWidgets.QLabel(parent=self.nhomThongTin)
        self.lblMaTT.setObjectName("lblMaTT")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lblMaTT)
        self.lblTitleOrderID = QtWidgets.QLabel(parent=self.nhomThongTin)
        self.lblTitleOrderID.setObjectName("lblTitleOrderID")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblTitleOrderID)
        self.lblMaDH = QtWidgets.QLabel(parent=self.nhomThongTin)
        self.lblMaDH.setObjectName("lblMaDH")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lblMaDH)
        self.lblTitleCustomer = QtWidgets.QLabel(parent=self.nhomThongTin)
        self.lblTitleCustomer.setObjectName("lblTitleCustomer")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblTitleCustomer)
        self.lblTenKH = QtWidgets.QLabel(parent=self.nhomThongTin)
        self.lblTenKH.setObjectName("lblTenKH")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lblTenKH)
        self.lblTitleMethod = QtWidgets.QLabel(parent=self.nhomThongTin)
        self.lblTitleMethod.setObjectName("lblTitleMethod")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblTitleMethod)
        self.lblPhuongThucThanhToan = QtWidgets.QLabel(parent=self.nhomThongTin)
        self.lblPhuongThucThanhToan.setObjectName("lblPhuongThucThanhToan")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lblPhuongThucThanhToan)
        self.lblTitleDate = QtWidgets.QLabel(parent=self.nhomThongTin)
        self.lblTitleDate.setObjectName("lblTitleDate")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblTitleDate)
        self.lblngayTT = QtWidgets.QLabel(parent=self.nhomThongTin)
        self.lblngayTT.setObjectName("lblngayTT")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lblngayTT)
        self.lblTitleStatus = QtWidgets.QLabel(parent=self.nhomThongTin)
        self.lblTitleStatus.setObjectName("lblTitleStatus")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblTitleStatus)
        self.lblTrangThaiTT = QtWidgets.QLabel(parent=self.nhomThongTin)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblTrangThaiTT.setFont(font)
        self.lblTrangThaiTT.setObjectName("lblTrangThaiTT")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lblTrangThaiTT)
        self.mainVerticalLayout.addWidget(self.nhomThongTin)
        self.nhomSoTien = QtWidgets.QGroupBox(parent=hopThoaiThanhToanChiTiet)
        self.nhomSoTien.setObjectName("nhomSoTien")
        self.amountLayout = QtWidgets.QVBoxLayout(self.nhomSoTien)
        self.amountLayout.setObjectName("amountLayout")
        self.lblTongTien = QtWidgets.QLabel(parent=self.nhomSoTien)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lblTongTien.setFont(font)
        self.lblTongTien.setStyleSheet("color: #E53935;")
        self.lblTongTien.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblTongTien.setObjectName("lblTongTien")
        self.amountLayout.addWidget(self.lblTongTien)
        self.mainVerticalLayout.addWidget(self.nhomSoTien)
        self.phanTuBottom = QtWidgets.QFrame(parent=hopThoaiThanhToanChiTiet)
        self.phanTuBottom.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.phanTuBottom.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.phanTuBottom.setObjectName("phanTuBottom")
        self.mainVerticalLayout.addWidget(self.phanTuBottom)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        spacerItem = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.buttonLayout.addItem(spacerItem)
        self.btnXacNhanTT = QtWidgets.QPushButton(parent=hopThoaiThanhToanChiTiet)
        self.btnXacNhanTT.setObjectName("btnXacNhanTT")
        self.buttonLayout.addWidget(self.btnXacNhanTT)
        self.btnClose = QtWidgets.QPushButton(parent=hopThoaiThanhToanChiTiet)
        self.btnClose.setObjectName("btnClose")
        self.buttonLayout.addWidget(self.btnClose)
        self.mainVerticalLayout.addLayout(self.buttonLayout)

        self.retranslateUi(hopThoaiThanhToanChiTiet)
        QtCore.QMetaObject.connectSlotsByName(hopThoaiThanhToanChiTiet)

    def retranslateUi(self, hopThoaiThanhToanChiTiet):
        _translate = QtCore.QCoreApplication.translate
        hopThoaiThanhToanChiTiet.setWindowTitle(_translate("hopThoaiThanhToanChiTiet", "Thông tin chi tiết thanh toán"))
        self.lblHeader.setText(_translate("hopThoaiThanhToanChiTiet", "HÓA ĐƠN THANH TOÁN BÁN HÀNG"))
        self.nhomThongTin.setTitle(_translate("hopThoaiThanhToanChiTiet", "Thông tin giao dịch"))
        self.lblTitlePayID.setText(_translate("hopThoaiThanhToanChiTiet", "Mã thanh toán:"))
        self.lblMaTT.setText(_translate("hopThoaiThanhToanChiTiet", "PAY00000"))
        self.lblTitleOrderID.setText(_translate("hopThoaiThanhToanChiTiet", "Mã đơn hàng:"))
        self.lblMaDH.setText(_translate("hopThoaiThanhToanChiTiet", "ORD00000"))
        self.lblTitleCustomer.setText(_translate("hopThoaiThanhToanChiTiet", "Khách hàng:"))
        self.lblTenKH.setText(_translate("hopThoaiThanhToanChiTiet", "N/A"))
        self.lblTitleMethod.setText(_translate("hopThoaiThanhToanChiTiet", "Phương thức:"))
        self.lblPhuongThucThanhToan.setText(_translate("hopThoaiThanhToanChiTiet", "Chưa xác định"))
        self.lblTitleDate.setText(_translate("hopThoaiThanhToanChiTiet", "Ngày thanh toán:"))
        self.lblngayTT.setText(_translate("hopThoaiThanhToanChiTiet", "--/--/----"))
        self.lblTitleStatus.setText(_translate("hopThoaiThanhToanChiTiet", "Trạng thái:"))
        self.lblTrangThaiTT.setText(_translate("hopThoaiThanhToanChiTiet", "Chưa thanh toán"))
        self.nhomSoTien.setTitle(_translate("hopThoaiThanhToanChiTiet", "Tổng tiền thu (VND)"))
        self.lblTongTien.setText(_translate("hopThoaiThanhToanChiTiet", "0 VND"))
        self.btnXacNhanTT.setText(_translate("hopThoaiThanhToanChiTiet", "Xác Nhận Thanh Toán"))
        self.btnClose.setText(_translate("hopThoaiThanhToanChiTiet", "Đóng"))
