---RÀNG BUỘC KHÓA CHÍNH CHO BẢNG CUSTOMER
ALTER TABLE Customer ADD CONSTRAINT pk_Customer PRIMARY KEY (CustomerID)

---RÀNG BUỘC KHÓA CHÍNH CHO BẢNG INDIVIDUAL_CUSTOMER
ALTER TABLE  Individual_Customer ADD CONSTRAIN pk_Individual_Customer  PRIMARY KEY (ICustomerID)

---RÀNG BUỘC KHÓA CHÍNH CHO BẢNG BUSINESS_CUSTOMER
ALTER TABLE Business_Customer ADD CONSTRAINT pk_Business_Customer PRIMARY KEY (BCustomerID)


---RÀNG BUỘC KHÓA CHÍNH CHO BẢNG CATEGORY
ALTER TABLE Category ADD CONSTRAINT pk_Category PRIMARY KEY (CategoryID)

---RÀNG BUỘC KHÓA CHÍNH CHO BẢNG PRODUCT
ALTER TABLE Product ADD CONSTRAINT pk_Product PRIMARY KEY (ProductID)

---RÀNG BUỘC KHÓA CHÍNH CHO BẢNG WAREHOUSE
ALTER TABLE Warehouse ADD CONSTRAINT pk_Warehouse PRIMARY KEY (WarehouseID)

---RÀNG BUỘC KHÓA CHÍNH CHO BẢNG INVENTORY
ALTER TABLE Inventory ADD CONSTRAINT pk_Inventory PRIMARY KEY (WarehouseID, ProductID)

---RÀNG BUỘC KHÓA CHÍNH CHO BẢNG EMPLOYEE
ALTER TABLE Employee ADD CONSTRAINT pk_Employee PRIMARY KEY (EmployeeID)

---RÀNG BUỘC KHÓA CHÍNH CHO BẢNG ROLE
ALTER TABLE [Role] ADD CONSTRAINT pk_Role PRIMARY KEY (RoleID)

---RÀNG BUỘC KHÓA CHÍNH CHO BẢNG ACCOUNT
ALTER TABLE Account ADD CONSTRAINT pk_Account PRIMARY KEY (AccountID)

---RÀNG BUỘC KHÓA CHÍNH CHO BẢNG ORDER
ALTER TABLE [Order] ADD CONSTRAINT pk_Order PRIMARY KEY (OrderID)

---RÀNG BUỘC KHÓA CHÍNH CHO BẢNG ORDER_DETAIL
ALTER TABLE Order_Detail ADD CONSTRAINT pk_Order_Detail PRIMARY KEY (OrderID, ProductID)

---RÀNG BUỘC KHÓA CHÍNH CHO BẢNG PAYMENT
ALTER TABLE Payment ADD CONSTRAINT pk_Payments PRIMARY KEY (PaymentID)

---RÀNG BUỘC KHÓA CHÍNH CHO BẢNG DELIVERY_PARTNER
ALTER TABLE Delivery_Partner ADD CONSTRAINT pk_Delivery_Partner PRIMARY KEY (PartnerID)

---RÀNG BUỘC KHÓA CHÍNH CHO BẢNG SHIPMENT
ALTER TABLE Shipment ADD CONSTRAINT pk_Shipment PRIMARY KEY (ShipmentID)
