USE QL_BANHANG_KHOHANG

---RÀNG BUỘC KHÓA NGOẠI CHO BẢNG INDIVIDUAL_CUSTOMER
ALTER TABLE Individual_Customer
ADD CONSTRAINT fk_Individual_Customer_Customer
FOREIGN KEY (ICustomerID) REFERENCES Customer(CustomerID)

---RÀNG BUỘC KHÓA NGOẠI CHO BẢNG BUSINESS_CUSTOMER
ALTER TABLE Business_customer
ADD CONSTRAINT fk_Business_Customer_Customer
FOREIGN KEY (BCustomerID) REFERENCES Customer(CustomerID)

---RÀNG BUỘC KHÓA NGOẠI CHO BẢNG PRODUCT
ALTER TABLE Product
ADD CONSTRAINT fk_Product_Category
FOREIGN KEY (CategoryID) REFERENCES Category(CategoryID)

---RÀNG BUỘC KHÓA NGOẠI CHO BẢNG INVENTORY - WAREHOUSE
ALTER TABLE Inventory
ADD CONSTRAINT fk_Inventory_Warehouse
FOREIGN KEY (WarehouseID) REFERENCES Warehouse(WarehouseID)

---RÀNG BUỘC KHÓA NGOẠI CHO BẢNG INVENTORY - PRODUCT
ALTER TABLE Inventory
ADD CONSTRAINT fk_Inventory_Product
FOREIGN KEY (ProductID) REFERENCES Product(ProductID)

---RÀNG BUỘC KHÓA NGOẠI CHO BẢNG ACCOUNT - EMPLOYEE
ALTER TABLE Account
ADD CONSTRAINT fk_Account_Employee
FOREIGN KEY (EmployeeID) REFERENCES Employee(EmployeeID)

---RÀNG BUỘC KHÓA NGOẠI CHO BẢNG ACCOUNT - ROLE
ALTER TABLE Account
ADD CONSTRAINT fk_Account_Role
FOREIGN KEY (RoleID) REFERENCES [Role](RoleID)

---RÀNG BUỘC KHÓA NGOẠI CHO BẢNG ORDER - CUSTOMER
ALTER TABLE [Order]
ADD CONSTRAINT fk_Order_Customer
FOREIGN KEY (CustomerID) REFERENCES Customer(CustomerID)

---RÀNG BUỘC KHÓA NGOẠI CHO BẢNG ORDER - EMPLOYEE
ALTER TABLE [Order]
ADD CONSTRAINT fk_Order_Employee
FOREIGN KEY (EmployeeID) REFERENCES Employee(EmployeeID)

---RÀNG BUỘC KHÓA NGOẠI CHO BẢNG ORDER_DETAIL - ORDER
ALTER TABLE Order_Detail
ADD CONSTRAINT fk_Order_Detail_Order
FOREIGN KEY (OrderID) REFERENCES [Order](OrderID)

---RÀNG BUỘC KHÓA NGOẠI CHO BẢNG ORDER_DETAIL - PRODUCT
ALTER TABLE Order_Detail
ADD CONSTRAINT fk_Order_Detail_Product
FOREIGN KEY (ProductID) REFERENCES Product(ProductID)

---RÀNG BUỘC KHÓA NGOẠI CHO BẢNG PAYMENT - ORDER
ALTER TABLE Payment
ADD CONSTRAINT fk_Payment_Order
FOREIGN KEY (OrderID) REFERENCES [Order](OrderID)

---RÀNG BUỘC KHÓA NGOẠI CHO BẢNG SHIPMENT - ORDER
ALTER TABLE Shipment
ADD CONSTRAINT fk_Shipment_Order
FOREIGN KEY (OrderID) REFERENCES [Order](OrderID)

---RÀNG BUỘC KHÓA NGOẠI CHO BẢNG SHIPMENT - DELIVERY_PARTNER
ALTER TABLE Shipment
ADD CONSTRAINT fk_Shipment_Delivery_Partner
FOREIGN KEY (PartnerID) REFERENCES Delivery_Partner(PartnerID)

---RÀNG BUỘC KHÓA NGOẠI CHO BẢNG SHIPMENT - EMPLOYEE
ALTER TABLE Shipment
ADD CONSTRAINT fk_Shipment_Employee
FOREIGN KEY (EmployeeID) REFERENCES Employee(EmployeeID)

--RÀNG BUỘC KHÓA NGOẠI CHO BẢNG PRT_SHIPPING_METHODS
ALTER TABLE Prt_Shipping_Methods
ADD CONSTRAINT fk_Prt_Shipping_Methods
FOREIGN KEY (PartnerID) REFERENCES Delivery_Partner(PartnerID)