# Form implementation generated from reading ui file 'ui/partner_add.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_PartnerAddDialog(object):
    def setupUi(self, PartnerAddDialog):
        PartnerAddDialog.setObjectName("PartnerAddDialog")
        PartnerAddDialog.resize(417, 423)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui\\../resources/icons/square-plus.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        PartnerAddDialog.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(PartnerAddDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.grpPartnerInfo = QtWidgets.QGroupBox(parent=PartnerAddDialog)
        self.grpPartnerInfo.setObjectName("grpPartnerInfo")
        self.formLayout = QtWidgets.QFormLayout(self.grpPartnerInfo)
        self.formLayout.setObjectName("formLayout")
        self.lblPartnerID = QtWidgets.QLabel(parent=self.grpPartnerInfo)
        self.lblPartnerID.setObjectName("lblPartnerID")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblPartnerID)
        self.txtMaDT = QtWidgets.QLineEdit(parent=self.grpPartnerInfo)
        self.txtMaDT.setReadOnly(True)
        self.txtMaDT.setObjectName("txtMaDT")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.txtMaDT)
        self.lblPartnerName = QtWidgets.QLabel(parent=self.grpPartnerInfo)
        self.lblPartnerName.setObjectName("lblPartnerName")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblPartnerName)
        self.txtTenDT = QtWidgets.QLineEdit(parent=self.grpPartnerInfo)
        self.txtTenDT.setObjectName("txtTenDT")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.txtTenDT)
        self.lblPhone = QtWidgets.QLabel(parent=self.grpPartnerInfo)
        self.lblPhone.setObjectName("lblPhone")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblPhone)
        self.txtSDT_DT = QtWidgets.QLineEdit(parent=self.grpPartnerInfo)
        self.txtSDT_DT.setObjectName("txtSDT_DT")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.txtSDT_DT)
        self.lblEmail = QtWidgets.QLabel(parent=self.grpPartnerInfo)
        self.lblEmail.setObjectName("lblEmail")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblEmail)
        self.txtEmai_DT = QtWidgets.QLineEdit(parent=self.grpPartnerInfo)
        self.txtEmai_DT.setObjectName("txtEmai_DT")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.txtEmai_DT)
        self.lblAddress = QtWidgets.QLabel(parent=self.grpPartnerInfo)
        self.lblAddress.setObjectName("lblAddress")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblAddress)
        self.txtDiaChiDT = QtWidgets.QLineEdit(parent=self.grpPartnerInfo)
        self.txtDiaChiDT.setObjectName("txtDiaChiDT")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.txtDiaChiDT)
        self.label = QtWidgets.QLabel(parent=self.grpPartnerInfo)
        self.label.setObjectName("label")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
        self.rbTieuchuan = QtWidgets.QCheckBox(parent=self.grpPartnerInfo)
        self.rbTieuchuan.setObjectName("rbTieuchuan")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.FieldRole, self.rbTieuchuan)
        self.rbTietKiem = QtWidgets.QCheckBox(parent=self.grpPartnerInfo)
        self.rbTietKiem.setObjectName("rbTietKiem")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.ItemRole.FieldRole, self.rbTietKiem)
        self.rbHoaToc = QtWidgets.QCheckBox(parent=self.grpPartnerInfo)
        self.rbHoaToc.setObjectName("rbHoaToc")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.ItemRole.FieldRole, self.rbHoaToc)
        self.verticalLayout.addWidget(self.grpPartnerInfo)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setContentsMargins(-1, 25, -1, 25)
        self.buttonLayout.setObjectName("buttonLayout")
        spacerItem = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.buttonLayout.addItem(spacerItem)
        self.btnLuuDT = QtWidgets.QPushButton(parent=PartnerAddDialog)
        self.btnLuuDT.setObjectName("btnLuuDT")
        self.buttonLayout.addWidget(self.btnLuuDT)
        self.btnHuyDT = QtWidgets.QPushButton(parent=PartnerAddDialog)
        self.btnHuyDT.setObjectName("btnHuyDT")
        self.buttonLayout.addWidget(self.btnHuyDT)
        self.verticalLayout.addLayout(self.buttonLayout)

        self.retranslateUi(PartnerAddDialog)
        QtCore.QMetaObject.connectSlotsByName(PartnerAddDialog)

    def retranslateUi(self, PartnerAddDialog):
        _translate = QtCore.QCoreApplication.translate
        PartnerAddDialog.setWindowTitle(_translate("PartnerAddDialog", "Đối tác vận chuyển"))
        self.grpPartnerInfo.setTitle(_translate("PartnerAddDialog", "Thông tin đối tác"))
        self.lblPartnerID.setText(_translate("PartnerAddDialog", "Mã đối tác"))
        self.lblPartnerName.setText(_translate("PartnerAddDialog", "Tên đối tác"))
        self.lblPhone.setText(_translate("PartnerAddDialog", "SĐT"))
        self.lblEmail.setText(_translate("PartnerAddDialog", "Email"))
        self.lblAddress.setText(_translate("PartnerAddDialog", "Địa chỉ"))
        self.label.setText(_translate("PartnerAddDialog", "Phương thức vận chuyển"))
        self.rbTieuchuan.setText(_translate("PartnerAddDialog", "Tiêu chuẩn"))
        self.rbTietKiem.setText(_translate("PartnerAddDialog", "Tiết kiệm"))
        self.rbHoaToc.setText(_translate("PartnerAddDialog", "Hỏa tốc"))
        self.btnLuuDT.setText(_translate("PartnerAddDialog", "Lưu"))
        self.btnHuyDT.setText(_translate("PartnerAddDialog", "Hủy"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PartnerAddDialog = QtWidgets.QDialog()
    ui = Ui_PartnerAddDialog()
    ui.setupUi(PartnerAddDialog)
    PartnerAddDialog.show()
    sys.exit(app.exec())
