# Form implementation generated from reading ui file 'ui/order_add_ord_detail.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_hopThoaiDonHangMuc(object):
    def setupUi(self, hopThoaiDonHangMuc):
        hopThoaiDonHangMuc.setObjectName("hopThoaiDonHangMuc")
        hopThoaiDonHangMuc.resize(386, 319)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui\\../resources/icons/square-plus.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        hopThoaiDonHangMuc.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(hopThoaiDonHangMuc)
        self.verticalLayout.setObjectName("verticalLayout")
        self.nhomSanPham = QtWidgets.QGroupBox(parent=hopThoaiDonHangMuc)
        self.nhomSanPham.setObjectName("nhomSanPham")
        self.formLayout = QtWidgets.QFormLayout(self.nhomSanPham)
        self.formLayout.setObjectName("formLayout")
        self.lblProduct = QtWidgets.QLabel(parent=self.nhomSanPham)
        self.lblProduct.setObjectName("lblProduct")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblProduct)
        self.cbbSanPham = QtWidgets.QComboBox(parent=self.nhomSanPham)
        self.cbbSanPham.setEditable(False)
        self.cbbSanPham.setObjectName("cbbSanPham")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.cbbSanPham)
        self.lblStock = QtWidgets.QLabel(parent=self.nhomSanPham)
        self.lblStock.setObjectName("lblStock")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblStock)
        self.txtTonKho = QtWidgets.QLineEdit(parent=self.nhomSanPham)
        self.txtTonKho.setReadOnly(True)
        self.txtTonKho.setObjectName("txtTonKho")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.txtTonKho)
        self.lblQuantity = QtWidgets.QLabel(parent=self.nhomSanPham)
        self.lblQuantity.setObjectName("lblQuantity")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblQuantity)
        self.spinSpinSoLuong = QtWidgets.QSpinBox(parent=self.nhomSanPham)
        self.spinSpinSoLuong.setMinimum(1)
        self.spinSpinSoLuong.setMaximum(9999)
        self.spinSpinSoLuong.setObjectName("spinSpinSoLuong")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.spinSpinSoLuong)
        self.label = QtWidgets.QLabel(parent=self.nhomSanPham)
        self.label.setObjectName("label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
        self.cbbKhoSP = QtWidgets.QComboBox(parent=self.nhomSanPham)
        self.cbbKhoSP.setObjectName("cbbKhoSP")
        self.cbbKhoSP.addItem("")
        self.cbbKhoSP.setItemText(0, "")
        self.cbbKhoSP.addItem("")
        self.cbbKhoSP.addItem("")
        self.cbbKhoSP.addItem("")
        self.cbbKhoSP.addItem("")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.cbbKhoSP)
        self.verticalLayout.addWidget(self.nhomSanPham)
        self.hboxlayout = QtWidgets.QHBoxLayout()
        self.hboxlayout.setObjectName("hboxlayout")
        spacerItem = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.hboxlayout.addItem(spacerItem)
        self.btnLuu_Order_detail = QtWidgets.QPushButton(parent=hopThoaiDonHangMuc)
        self.btnLuu_Order_detail.setObjectName("btnLuu_Order_detail")
        self.hboxlayout.addWidget(self.btnLuu_Order_detail)
        self.btnHuyOrder_Detail = QtWidgets.QPushButton(parent=hopThoaiDonHangMuc)
        self.btnHuyOrder_Detail.setObjectName("btnHuyOrder_Detail")
        self.hboxlayout.addWidget(self.btnHuyOrder_Detail)
        self.verticalLayout.addLayout(self.hboxlayout)
        self.verticalLayout.setStretch(0, 5)
        self.verticalLayout.setStretch(1, 1)

        self.retranslateUi(hopThoaiDonHangMuc)
        QtCore.QMetaObject.connectSlotsByName(hopThoaiDonHangMuc)

    def retranslateUi(self, hopThoaiDonHangMuc):
        _translate = QtCore.QCoreApplication.translate
        hopThoaiDonHangMuc.setWindowTitle(_translate("hopThoaiDonHangMuc", "Thêm Sản Phẩm Vào Đơn Hàng"))
        self.nhomSanPham.setTitle(_translate("hopThoaiDonHangMuc", "Thông Tin Sản Phẩm"))
        self.lblProduct.setText(_translate("hopThoaiDonHangMuc", "Sản phẩm"))
        self.lblStock.setText(_translate("hopThoaiDonHangMuc", "Mã SP"))
        self.lblQuantity.setText(_translate("hopThoaiDonHangMuc", "Số lượng"))
        self.label.setText(_translate("hopThoaiDonHangMuc", "Kho"))
        self.cbbKhoSP.setItemText(1, _translate("hopThoaiDonHangMuc", "Kho Tân Bình"))
        self.cbbKhoSP.setItemText(2, _translate("hopThoaiDonHangMuc", "Kho Thủ Đức "))
        self.cbbKhoSP.setItemText(3, _translate("hopThoaiDonHangMuc", "Kho Bình Tân "))
        self.cbbKhoSP.setItemText(4, _translate("hopThoaiDonHangMuc", "Kho Tổng Củ Chi"))
        self.btnLuu_Order_detail.setText(_translate("hopThoaiDonHangMuc", "Lưu"))
        self.btnHuyOrder_Detail.setText(_translate("hopThoaiDonHangMuc", "Hủy"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    hopThoaiDonHangMuc = QtWidgets.QDialog()
    ui = Ui_hopThoaiDonHangMuc()
    ui.setupUi(hopThoaiDonHangMuc)
    hopThoaiDonHangMuc.show()
    sys.exit(app.exec())
