# Form implementation generated from reading ui file 'ui/inventory_detail.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtWidgets
from .inventory_detail_ui import Ui_pageTonKho


class InventoryDetailDialog(QtWidgets.QDialog, Ui_pageTonKho):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.setupUi(self)
        self.item = None
        self.btnCapNhatTK.clicked.connect(self.on_update)

    def fill_item(self, item):
        self.item = item
        self.txtMaSPTK.setText(item.get("maSP", ""))
        self.txtTenSPTK.setText(item.get("tenSP", ""))
        self.txtDanhMucTK.setText(item.get("danhMuc", ""))
        self.txtDonViTinhTK.setText(item.get("donViTinh", ""))
        self.txtTonKhoTK.setText(str(item.get("tonKho", 0)))
        self.txtTrangThaiTK.setText(item.get("trangThai", ""))
        self.txtCapNhatTK.setText(item.get("capNhatGanNhat", ""))
        self.txtMaSPTK.setReadOnly(True)
        self.txtTenSPTK.setReadOnly(True)
        self.txtDanhMucTK.setReadOnly(True)
        self.txtDonViTinhTK.setReadOnly(True)
        self.txtTonKhoTK.setReadOnly(True)
        self.txtTrangThaiTK.setReadOnly(True)
        self.txtCapNhatTK.setReadOnly(True)
        self.tblLichSuTK.setRowCount(0)
        for history in item.get("history", []):
            row = self.tblLichSuTK.rowCount()
            self.tblLichSuTK.insertRow(row)
            self.tblLichSuTK.setItem(row, 0, QtWidgets.QTableWidgetItem(history.get("ngay", "")))
            self.tblLichSuTK.setItem(row, 1, QtWidgets.QTableWidgetItem(history.get("loai", "")))
            self.tblLichSuTK.setItem(row, 2, QtWidgets.QTableWidgetItem(str(history.get("soLuong", 0))))
            self.tblLichSuTK.setItem(row, 3, QtWidgets.QTableWidgetItem(history.get("nhanVien", "")))
            self.tblLichSuTK.setItem(row, 4, QtWidgets.QTableWidgetItem(history.get("ghiChu", "")))

    def on_update(self):
        if self.parent() is not None and hasattr(self.parent(), "open_inventory_update"):
            self.parent().open_inventory_update(self.item)
        self.accept()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dlg = InventoryDetailDialog()
    dlg.show()
    sys.exit(app.exec())
