# Form implementation generated from reading ui file 'ui/inventory_update.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, dlgDieuChinhTK):
        dlgDieuChinhTK.setObjectName("dlgDieuChinhTK")
        dlgDieuChinhTK.setGeometry(QtCore.QRect(0, 0, 445, 357))
        self.verticalLayout = QtWidgets.QVBoxLayout(dlgDieuChinhTK)
        self.verticalLayout.setObjectName("verticalLayout")
        self.nhomMacDinh = QtWidgets.QGroupBox(parent=dlgDieuChinhTK)
        self.nhomMacDinh.setObjectName("nhomMacDinh")
        self.formLayout = QtWidgets.QFormLayout(self.nhomMacDinh)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(parent=self.nhomMacDinh)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.rbTangTK = QtWidgets.QRadioButton(parent=self.nhomMacDinh)
        self.rbTangTK.setObjectName("rbTangTK")
        self.horizontalLayout.addWidget(self.rbTangTK)
        self.rbGiamTK = QtWidgets.QRadioButton(parent=self.nhomMacDinh)
        self.rbGiamTK.setObjectName("rbGiamTK")
        self.horizontalLayout.addWidget(self.rbGiamTK)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.horizontalLayout)
        self.label_2 = QtWidgets.QLabel(parent=self.nhomMacDinh)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)
        self.txtSoLuongTK = QtWidgets.QLineEdit(parent=self.nhomMacDinh)
        font = QtGui.QFont()
        font.setStrikeOut(False)
        self.txtSoLuongTK.setFont(font)
        self.txtSoLuongTK.setTabletTracking(False)
        self.txtSoLuongTK.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhNone)
        self.txtSoLuongTK.setObjectName("txtSoLuongTK")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.txtSoLuongTK)
        self.label_3 = QtWidgets.QLabel(parent=self.nhomMacDinh)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_3)
        self.txtGhiChuTK = QtWidgets.QPlainTextEdit(parent=self.nhomMacDinh)
        self.txtGhiChuTK.setObjectName("txtGhiChuTK")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.txtGhiChuTK)
        self.verticalLayout.addWidget(self.nhomMacDinh)
        self.hboxlayout = QtWidgets.QHBoxLayout()
        self.hboxlayout.setObjectName("hboxlayout")
        spacerItem = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.hboxlayout.addItem(spacerItem)
        self.btnLuuTK = QtWidgets.QPushButton(parent=dlgDieuChinhTK)
        self.btnLuuTK.setObjectName("btnLuuTK")
        self.hboxlayout.addWidget(self.btnLuuTK)
        self.btnHuyTK = QtWidgets.QPushButton(parent=dlgDieuChinhTK)
        self.btnHuyTK.setObjectName("btnHuyTK")
        self.hboxlayout.addWidget(self.btnHuyTK)
        self.verticalLayout.addLayout(self.hboxlayout)

        self.retranslateUi(dlgDieuChinhTK)
        QtCore.QMetaObject.connectSlotsByName(dlgDieuChinhTK)

    def retranslateUi(self, dlgDieuChinhTK):
        _translate = QtCore.QCoreApplication.translate
        dlgDieuChinhTK.setWindowTitle(_translate("Dialog", "Dialog"))
        self.nhomMacDinh.setTitle(_translate("Dialog", "Điều Chỉnh Tồn Kho"))
        self.label.setText(_translate("Dialog", "Loại Điều Chỉnh"))
        self.rbTangTK.setText(_translate("Dialog", "Tăng"))
        self.rbGiamTK.setText(_translate("Dialog", "Giảm"))
        self.label_2.setText(_translate("Dialog", "Số Lượng"))
        self.label_3.setText(_translate("Dialog", "Ghi Chú"))
        self.btnLuuTK.setText(_translate("Dialog", "Lưu"))
        self.btnHuyTK.setText(_translate("Dialog", "Hủy"))


class InventoryUpdateDialog(QtWidgets.QDialog, Ui_Dialog):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.setupUi(self)
        self.item = None
        self.rbTangTK.setChecked(True)
        self.btnLuuTK.clicked.connect(self.on_save)
        self.btnHuyTK.clicked.connect(self.reject)

    def prepare_for_update(self, item):
        self.item = item
        self.txtSoLuongTK.clear()
        self.txtGhiChuTK.clear()
        self.rbTangTK.setChecked(True)

    def on_save(self):
        if self.item is None:
            return
        try:
            quantity = int(self.txtSoLuongTK.text().strip())
        except Exception:
            QtWidgets.QMessageBox.warning(self, "Lỗi", "Số lượng phải là số nguyên.")
            return
        if quantity <= 0:
            QtWidgets.QMessageBox.warning(self, "Lỗi", "Số lượng phải lớn hơn 0.")
            return
        mode = "Tăng" if self.rbTangTK.isChecked() else "Giảm"
        note = self.txtGhiChuTK.toPlainText().strip() or "Không có ghi chú"
        if self.parent() is not None and hasattr(self.parent(), "apply_inventory_adjustment"):
            self.parent().apply_inventory_adjustment(self.item, mode, quantity, note)
        self.accept()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dlgDieuChinhTK = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(dlgDieuChinhTK)
    dlgDieuChinhTK.show()
    sys.exit(app.exec())
