# Form implementation generated from reading ui file 'ui/inventory_update.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtWidgets
from .inventory_update_ui import Ui_Dialog


class InventoryUpdateDialog(QtWidgets.QDialog, Ui_Dialog):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.setupUi(self)
        self.item = None
        self.rbTangTK.setChecked(True)
        self.btnLuuTK.clicked.connect(self.on_save)
        self.btnHuyTK.clicked.connect(self.reject)

    def prepare_for_update(self, item):
        self.item = item
        self.txtSoLuongTK.clear()
        self.txtGhiChuTK.clear()
        self.rbTangTK.setChecked(True)

    def on_save(self):
        if self.item is None:
            return
        try:
            quantity = int(self.txtSoLuongTK.text().strip())
        except Exception:
            QtWidgets.QMessageBox.warning(self, "Lỗi", "Số lượng phải là số nguyên.")
            return
        if quantity <= 0:
            QtWidgets.QMessageBox.warning(self, "Lỗi", "Số lượng phải lớn hơn 0.")
            return
        mode = "Tăng" if self.rbTangTK.isChecked() else "Giảm"
        note = self.txtGhiChuTK.toPlainText().strip() or "Không có ghi chú"
        if self.parent() is not None and hasattr(self.parent(), "apply_inventory_adjustment"):
            self.parent().apply_inventory_adjustment(self.item, mode, quantity, note)
        self.accept()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dlg = InventoryUpdateDialog()
    dlg.show()
    sys.exit(app.exec())
