# Form implementation generated from reading ui file 'ui/inventory_detail.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_pageTonKho(object):
    def setupUi(self, pageTonKho):
        pageTonKho.setObjectName("pageTonKho")
        pageTonKho.resize(673, 587)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(pageTonKho)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.nhomMacDinh = QtWidgets.QGroupBox(parent=pageTonKho)
        self.nhomMacDinh.setObjectName("nhomMacDinh")
        self.formLayout = QtWidgets.QFormLayout(self.nhomMacDinh)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(parent=self.nhomMacDinh)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
        self.txtMaSPTK = QtWidgets.QLineEdit(parent=self.nhomMacDinh)
        self.txtMaSPTK.setObjectName("txtMaSPTK")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.txtMaSPTK)
        self.label_2 = QtWidgets.QLabel(parent=self.nhomMacDinh)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)
        self.txtTenSPTK = QtWidgets.QLineEdit(parent=self.nhomMacDinh)
        self.txtTenSPTK.setObjectName("txtTenSPTK")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.txtTenSPTK)
        self.label_3 = QtWidgets.QLabel(parent=self.nhomMacDinh)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_3)
        self.txtDanhMucTK = QtWidgets.QLineEdit(parent=self.nhomMacDinh)
        self.txtDanhMucTK.setObjectName("txtDanhMucTK")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.txtDanhMucTK)
        self.label_4 = QtWidgets.QLabel(parent=self.nhomMacDinh)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_4)
        self.txtDonViTinhTK = QtWidgets.QLineEdit(parent=self.nhomMacDinh)
        self.txtDonViTinhTK.setObjectName("txtDonViTinhTK")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.txtDonViTinhTK)
        self.label_5 = QtWidgets.QLabel(parent=self.nhomMacDinh)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_5)
        self.txtTonKhoTK = QtWidgets.QLineEdit(parent=self.nhomMacDinh)
        self.txtTonKhoTK.setObjectName("txtTonKhoTK")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.txtTonKhoTK)
        self.label_6 = QtWidgets.QLabel(parent=self.nhomMacDinh)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_6)
        self.txtTrangThaiTK = QtWidgets.QLineEdit(parent=self.nhomMacDinh)
        self.txtTrangThaiTK.setObjectName("txtTrangThaiTK")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.FieldRole, self.txtTrangThaiTK)
        self.label_7 = QtWidgets.QLabel(parent=self.nhomMacDinh)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_7)
        self.txtCapNhatTK = QtWidgets.QLineEdit(parent=self.nhomMacDinh)
        self.txtCapNhatTK.setObjectName("txtCapNhatTK")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.ItemRole.FieldRole, self.txtCapNhatTK)
        self.verticalLayout_2.addWidget(self.nhomMacDinh)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btnCapNhatTK = QtWidgets.QPushButton(parent=pageTonKho)
        self.btnCapNhatTK.setObjectName("btnCapNhatTK")
        self.horizontalLayout.addWidget(self.btnCapNhatTK)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.nhom2 = QtWidgets.QGroupBox(parent=pageTonKho)
        self.nhom2.setObjectName("nhom2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.nhom2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tblLichSuTK = QtWidgets.QTableWidget(parent=self.nhom2)
        self.tblLichSuTK.setObjectName("tblLichSuTK")
        self.tblLichSuTK.setColumnCount(5)
        self.tblLichSuTK.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblLichSuTK.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblLichSuTK.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblLichSuTK.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblLichSuTK.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblLichSuTK.setHorizontalHeaderItem(4, item)
        self.verticalLayout.addWidget(self.tblLichSuTK)
        self.verticalLayout_2.addWidget(self.nhom2)

        self.retranslateUi(pageTonKho)
        QtCore.QMetaObject.connectSlotsByName(pageTonKho)

    def retranslateUi(self, pageTonKho):
        _translate = QtCore.QCoreApplication.translate
        self.nhomMacDinh.setTitle(_translate("pageTonKho", "Thông Tin Tồn Kho"))
        self.label.setText(_translate("pageTonKho", "Mã SP"))
        self.label_2.setText(_translate("pageTonKho", "Tên SP"))
        self.label_3.setText(_translate("pageTonKho", "Danh Mục"))
        self.label_4.setText(_translate("pageTonKho", "Đơn Vị Tính"))
        self.label_5.setText(_translate("pageTonKho", "Tồn Kho"))
        self.label_6.setText(_translate("pageTonKho", "Trạng Thái"))
        self.label_7.setText(_translate("pageTonKho", "Cập Nhật Gần Nhất"))
        self.btnCapNhatTK.setText(_translate("pageTonKho", "Cập Nhật"))
        self.nhom2.setTitle(_translate("pageTonKho", "Lịch Sử Biến Động"))
        item = self.tblLichSuTK.horizontalHeaderItem(0)
        item.setText(_translate("pageTonKho", "Ngày"))
        item = self.tblLichSuTK.horizontalHeaderItem(1)
        item.setText(_translate("pageTonKho", "Loại"))
        item = self.tblLichSuTK.horizontalHeaderItem(2)
        item.setText(_translate("pageTonKho", "Số Lượng"))
        item = self.tblLichSuTK.horizontalHeaderItem(3)
        item.setText(_translate("pageTonKho", "Nhân Viên"))
        item = self.tblLichSuTK.horizontalHeaderItem(4)
        item.setText(_translate("pageTonKho", "Ghi Chú"))


class InventoryDetailDialog(QtWidgets.QDialog, Ui_pageTonKho):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.setupUi(self)
        self.item = None
        self.btnCapNhatTK.clicked.connect(self.on_update)

    def fill_item(self, item):
        self.item = item
        self.txtMaSPTK.setText(item.get("maSP", ""))
        self.txtTenSPTK.setText(item.get("tenSP", ""))
        self.txtDanhMucTK.setText(item.get("danhMuc", ""))
        self.txtDonViTinhTK.setText(item.get("donViTinh", ""))
        self.txtTonKhoTK.setText(str(item.get("tonKho", 0)))
        self.txtTrangThaiTK.setText(item.get("trangThai", ""))
        self.txtCapNhatTK.setText(item.get("capNhatGanNhat", ""))
        self.txtMaSPTK.setReadOnly(True)
        self.txtTenSPTK.setReadOnly(True)
        self.txtDanhMucTK.setReadOnly(True)
        self.txtDonViTinhTK.setReadOnly(True)
        self.txtTonKhoTK.setReadOnly(True)
        self.txtTrangThaiTK.setReadOnly(True)
        self.txtCapNhatTK.setReadOnly(True)
        self.tblLichSuTK.setRowCount(0)
        for history in item.get("history", []):
            row = self.tblLichSuTK.rowCount()
            self.tblLichSuTK.insertRow(row)
            self.tblLichSuTK.setItem(row, 0, QtWidgets.QTableWidgetItem(history.get("ngay", "")))
            self.tblLichSuTK.setItem(row, 1, QtWidgets.QTableWidgetItem(history.get("loai", "")))
            self.tblLichSuTK.setItem(row, 2, QtWidgets.QTableWidgetItem(str(history.get("soLuong", 0))))
            self.tblLichSuTK.setItem(row, 3, QtWidgets.QTableWidgetItem(history.get("nhanVien", "")))
            self.tblLichSuTK.setItem(row, 4, QtWidgets.QTableWidgetItem(history.get("ghiChu", "")))

    def on_update(self):
        if self.parent() is not None and hasattr(self.parent(), "open_inventory_update"):
            self.parent().open_inventory_update(self.item)
        self.accept()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    pageTonKho = QtWidgets.QWidget()
    ui = Ui_pageTonKho()
    ui.setupUi(pageTonKho)
    pageTonKho.show()
    sys.exit(app.exec())
