# Form implementation generated from reading ui file 'ui/main_window.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


import os
import sys

from PyQt6 import QtCore, QtGui, QtWidgets

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, PROJECT_ROOT)
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from database.database import Database
from modules.category.category_add import CategoryAddDialog
from modules.category.category_detail import CategoryDetailDialog
from modules.inventory.inventory_detail import InventoryDetailDialog
from modules.inventory.inventory_update import InventoryUpdateDialog
from modules.payment.payment_detail import PaymentDetailDialog


class Ui_phanTuChinhWindow(object):
    def setupUi(self, phanTuChinhWindow):
        phanTuChinhWindow.setObjectName("phanTuChinhWindow")
        phanTuChinhWindow.resize(1015, 669)
        self.khungCentralwidget = QtWidgets.QWidget(parent=phanTuChinhWindow)
        self.khungCentralwidget.setObjectName("khungCentralwidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.khungCentralwidget)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.khungSidebar = QtWidgets.QFrame(parent=self.khungCentralwidget)
        self.khungSidebar.setMinimumSize(QtCore.QSize(220, 0))
        self.khungSidebar.setMaximumSize(QtCore.QSize(220, 16777215))
        self.khungSidebar.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.khungSidebar.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.khungSidebar.setObjectName("khungSidebar")
        self.verticalLayout_sidebar = QtWidgets.QVBoxLayout(self.khungSidebar)
        self.verticalLayout_sidebar.setContentsMargins(12, 16, 12, 16)
        self.verticalLayout_sidebar.setSpacing(8)
        self.verticalLayout_sidebar.setObjectName("verticalLayout_sidebar")
        self.khungFrame = QtWidgets.QFrame(parent=self.khungSidebar)
        self.khungFrame.setMinimumSize(QtCore.QSize(20, 40))
        self.khungFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.khungFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.khungFrame.setObjectName("khungFrame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.khungFrame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=self.khungFrame)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.label = QtWidgets.QLabel(parent=self.khungFrame)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.verticalLayout_sidebar.addWidget(self.khungFrame)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.verticalLayout_sidebar.addItem(spacerItem)
        self.btnTongQuan = QtWidgets.QPushButton(parent=self.khungSidebar)
        self.btnTongQuan.setFlat(True)
        self.btnTongQuan.setObjectName("btnTongQuan")
        self.verticalLayout_sidebar.addWidget(self.btnTongQuan)
        self.btnDonhang = QtWidgets.QPushButton(parent=self.khungSidebar)
        self.btnDonhang.setFlat(True)
        self.btnDonhang.setObjectName("btnDonhang")
        self.verticalLayout_sidebar.addWidget(self.btnDonhang)
        self.btnKhachHang = QtWidgets.QPushButton(parent=self.khungSidebar)
        self.btnKhachHang.setFlat(True)
        self.btnKhachHang.setObjectName("btnKhachHang")
        self.verticalLayout_sidebar.addWidget(self.btnKhachHang)
        self.btnSanPham = QtWidgets.QPushButton(parent=self.khungSidebar)
        self.btnSanPham.setFlat(True)
        self.btnSanPham.setObjectName("btnSanPham")
        self.verticalLayout_sidebar.addWidget(self.btnSanPham)
        self.btnDanhMuc = QtWidgets.QPushButton(parent=self.khungSidebar)
        self.btnDanhMuc.setFlat(True)
        self.btnDanhMuc.setObjectName("btnDanhMuc")
        self.verticalLayout_sidebar.addWidget(self.btnDanhMuc)
        self.btnTonKho = QtWidgets.QPushButton(parent=self.khungSidebar)
        self.btnTonKho.setFlat(True)
        self.btnTonKho.setObjectName("btnTonKho")
        self.verticalLayout_sidebar.addWidget(self.btnTonKho)
        self.btnThanhToan = QtWidgets.QPushButton(parent=self.khungSidebar)
        self.btnThanhToan.setFlat(True)
        self.btnThanhToan.setObjectName("btnThanhToan")
        self.verticalLayout_sidebar.addWidget(self.btnThanhToan)
        self.btnVanChuyen = QtWidgets.QPushButton(parent=self.khungSidebar)
        self.btnVanChuyen.setFlat(True)
        self.btnVanChuyen.setObjectName("btnVanChuyen")
        self.verticalLayout_sidebar.addWidget(self.btnVanChuyen)
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.khungSidebar)
        self.pushButton_2.setFlat(True)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_sidebar.addWidget(self.pushButton_2)
        self.btnNhanVien = QtWidgets.QPushButton(parent=self.khungSidebar)
        self.btnNhanVien.setFlat(True)
        self.btnNhanVien.setObjectName("btnNhanVien")
        self.verticalLayout_sidebar.addWidget(self.btnNhanVien)
        self.btnBaoCao = QtWidgets.QPushButton(parent=self.khungSidebar)
        self.btnBaoCao.setFlat(True)
        self.btnBaoCao.setObjectName("btnBaoCao")
        self.verticalLayout_sidebar.addWidget(self.btnBaoCao)
        self.btnDangXuat = QtWidgets.QPushButton(parent=self.khungSidebar)
        self.btnDangXuat.setFlat(True)
        self.btnDangXuat.setObjectName("btnDangXuat")
        self.verticalLayout_sidebar.addWidget(self.btnDangXuat)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_sidebar.addItem(spacerItem1)
        self.horizontalLayout_5.addWidget(self.khungSidebar)
        self.khungChuyenTrangStacked = QtWidgets.QStackedWidget(parent=self.khungCentralwidget)
        self.khungChuyenTrangStacked.setObjectName("khungChuyenTrangStacked")
        self.pageTongQuan = QtWidgets.QWidget()
        self.pageTongQuan.setObjectName("pageTongQuan")
        self.khungChuyenTrangStacked.addWidget(self.pageTongQuan)
        self.pageDonHang = QtWidgets.QWidget()
        self.pageDonHang.setObjectName("pageDonHang")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.pageDonHang)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.nhomTimKiem2 = QtWidgets.QGroupBox(parent=self.pageDonHang)
        self.nhomTimKiem2.setObjectName("nhomTimKiem2")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.nhomTimKiem2)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.txtTimKiemDH = QtWidgets.QLineEdit(parent=self.nhomTimKiem2)
        self.txtTimKiemDH.setText("")
        self.txtTimKiemDH.setObjectName("txtTimKiemDH")
        self.horizontalLayout_6.addWidget(self.txtTimKiemDH)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.btnTimKiemDH = QtWidgets.QPushButton(parent=self.nhomTimKiem2)
        self.btnTimKiemDH.setObjectName("btnTimKiemDH")
        self.horizontalLayout_6.addWidget(self.btnTimKiemDH)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lblFromDate = QtWidgets.QLabel(parent=self.nhomTimKiem2)
        self.lblFromDate.setObjectName("lblFromDate")
        self.horizontalLayout_7.addWidget(self.lblFromDate)
        self.txtTuNgayDH = QtWidgets.QDateEdit(parent=self.nhomTimKiem2)
        self.txtTuNgayDH.setCalendarPopup(True)
        self.txtTuNgayDH.setObjectName("txtTuNgayDH")
        self.horizontalLayout_7.addWidget(self.txtTuNgayDH)
        self.lblToDate = QtWidgets.QLabel(parent=self.nhomTimKiem2)
        self.lblToDate.setObjectName("lblToDate")
        self.horizontalLayout_7.addWidget(self.lblToDate)
        self.txtDenNgayDH = QtWidgets.QDateEdit(parent=self.nhomTimKiem2)
        self.txtDenNgayDH.setCalendarPopup(True)
        self.txtDenNgayDH.setObjectName("txtDenNgayDH")
        self.horizontalLayout_7.addWidget(self.txtDenNgayDH)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8.addLayout(self.verticalLayout)
        spacerItem4 = QtWidgets.QSpacerItem(224, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem4)
        self.verticalLayout_4.addWidget(self.nhomTimKiem2)
        self.lblTitle_5 = QtWidgets.QLabel(parent=self.pageDonHang)
        self.lblTitle_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblTitle_5.setObjectName("lblTitle_5")
        self.verticalLayout_4.addWidget(self.lblTitle_5)
        self._2 = QtWidgets.QHBoxLayout()
        self._2.setObjectName("_2")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self._2.addItem(spacerItem5)
        self.btnThemDH = QtWidgets.QPushButton(parent=self.pageDonHang)
        self.btnThemDH.setObjectName("btnThemDH")
        self._2.addWidget(self.btnThemDH)
        self.btnCapNhatDH = QtWidgets.QPushButton(parent=self.pageDonHang)
        self.btnCapNhatDH.setObjectName("btnCapNhatDH")
        self._2.addWidget(self.btnCapNhatDH)
        self.btnXoaDH = QtWidgets.QPushButton(parent=self.pageDonHang)
        self.btnXoaDH.setObjectName("btnXoaDH")
        self._2.addWidget(self.btnXoaDH)
        self.btnRefreshSP_2 = QtWidgets.QPushButton(parent=self.pageDonHang)
        self.btnRefreshSP_2.setObjectName("btnRefreshSP_2")
        self._2.addWidget(self.btnRefreshSP_2)
        self.verticalLayout_4.addLayout(self._2)
        self.tblDonHang = QtWidgets.QTableWidget(parent=self.pageDonHang)
        self.tblDonHang.setObjectName("tblDonHang")
        self.tblDonHang.setColumnCount(6)
        self.tblDonHang.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblDonHang.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblDonHang.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblDonHang.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblDonHang.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblDonHang.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblDonHang.setHorizontalHeaderItem(5, item)
        self.verticalLayout_4.addWidget(self.tblDonHang)
        self.khungChuyenTrangStacked.addWidget(self.pageDonHang)
        self.pageKhachHang = QtWidgets.QWidget()
        self.pageKhachHang.setObjectName("pageKhachHang")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.pageKhachHang)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.nhomTimKiem = QtWidgets.QGroupBox(parent=self.pageKhachHang)
        self.nhomTimKiem.setObjectName("nhomTimKiem")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.nhomTimKiem)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.txtTimKiemKH = QtWidgets.QLineEdit(parent=self.nhomTimKiem)
        self.txtTimKiemKH.setObjectName("txtTimKiemKH")
        self.horizontalLayout_4.addWidget(self.txtTimKiemKH)
        self.btnTimKiemKH = QtWidgets.QPushButton(parent=self.nhomTimKiem)
        self.btnTimKiemKH.setObjectName("btnTimKiemKH")
        self.horizontalLayout_4.addWidget(self.btnTimKiemKH)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem7)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.lblTitle_3 = QtWidgets.QLabel(parent=self.nhomTimKiem)
        self.lblTitle_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblTitle_3.setObjectName("lblTitle_3")
        self.verticalLayout_2.addWidget(self.lblTitle_3)
        self.verticalLayout_3.addWidget(self.nhomTimKiem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem8)
        self.horizontalLayoutButtons = QtWidgets.QHBoxLayout()
        self.horizontalLayoutButtons.setObjectName("horizontalLayoutButtons")
        self.btnThemKH = QtWidgets.QPushButton(parent=self.pageKhachHang)
        self.btnThemKH.setObjectName("btnThemKH")
        self.horizontalLayoutButtons.addWidget(self.btnThemKH)
        self.btnChiTietKH = QtWidgets.QPushButton(parent=self.pageKhachHang)
        self.btnChiTietKH.setObjectName("btnChiTietKH")
        self.horizontalLayoutButtons.addWidget(self.btnChiTietKH)
        self.btnCapNhatKH = QtWidgets.QPushButton(parent=self.pageKhachHang)
        self.btnCapNhatKH.setObjectName("btnCapNhatKH")
        self.horizontalLayoutButtons.addWidget(self.btnCapNhatKH)
        self.btnXoaKH = QtWidgets.QPushButton(parent=self.pageKhachHang)
        self.btnXoaKH.setObjectName("btnXoaKH")
        self.horizontalLayoutButtons.addWidget(self.btnXoaKH)
        self.btnRefreshKH = QtWidgets.QPushButton(parent=self.pageKhachHang)
        self.btnRefreshKH.setObjectName("btnRefreshKH")
        self.horizontalLayoutButtons.addWidget(self.btnRefreshKH)
        self.horizontalLayout.addLayout(self.horizontalLayoutButtons)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.tblKhachHang = QtWidgets.QTableWidget(parent=self.pageKhachHang)
        self.tblKhachHang.setObjectName("tblKhachHang")
        self.tblKhachHang.setColumnCount(4)
        self.tblKhachHang.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblKhachHang.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblKhachHang.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblKhachHang.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblKhachHang.setHorizontalHeaderItem(3, item)
        self.tblKhachHang.horizontalHeader().setDefaultSectionSize(220)
        self.verticalLayout_3.addWidget(self.tblKhachHang)
        self.verticalLayout_3.setStretch(0, 2)
        self.verticalLayout_3.setStretch(1, 1)
        self.verticalLayout_3.setStretch(2, 8)
        self.khungChuyenTrangStacked.addWidget(self.pageKhachHang)
        self.pageSanPham = QtWidgets.QWidget()
        self.pageSanPham.setObjectName("pageSanPham")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.pageSanPham)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.nhomTimKiem21 = QtWidgets.QGroupBox(parent=self.pageSanPham)
        self.nhomTimKiem21.setObjectName("nhomTimKiem21")
        self._3 = QtWidgets.QGridLayout(self.nhomTimKiem21)
        self._3.setObjectName("_3")
        self.cbbTrangThai = QtWidgets.QComboBox(parent=self.nhomTimKiem21)
        self.cbbTrangThai.setObjectName("cbbTrangThai")
        self._3.addWidget(self.cbbTrangThai, 0, 5, 1, 1)
        self.btnTimKiemSP = QtWidgets.QPushButton(parent=self.nhomTimKiem21)
        self.btnTimKiemSP.setObjectName("btnTimKiemSP")
        self._3.addWidget(self.btnTimKiemSP, 0, 6, 1, 1)
        self.lblCategory = QtWidgets.QLabel(parent=self.nhomTimKiem21)
        self.lblCategory.setObjectName("lblCategory")
        self._3.addWidget(self.lblCategory, 0, 2, 1, 1)
        self.cbbDanhMuc = QtWidgets.QComboBox(parent=self.nhomTimKiem21)
        self.cbbDanhMuc.setObjectName("cbbDanhMuc")
        self._3.addWidget(self.cbbDanhMuc, 0, 3, 1, 1)
        self.lblStatus_2 = QtWidgets.QLabel(parent=self.nhomTimKiem21)
        self.lblStatus_2.setObjectName("lblStatus_2")
        self._3.addWidget(self.lblStatus_2, 0, 4, 1, 1)
        self.txtTimKiemSP = QtWidgets.QLineEdit(parent=self.nhomTimKiem21)
        self.txtTimKiemSP.setObjectName("txtTimKiemSP")
        self._3.addWidget(self.txtTimKiemSP, 0, 1, 1, 1)
        self.lblKeyword_2 = QtWidgets.QLabel(parent=self.nhomTimKiem21)
        self.lblKeyword_2.setObjectName("lblKeyword_2")
        self._3.addWidget(self.lblKeyword_2, 0, 0, 1, 1)
        self.verticalLayout_5.addWidget(self.nhomTimKiem21)
        self.lblTitle_4 = QtWidgets.QLabel(parent=self.pageSanPham)
        self.lblTitle_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblTitle_4.setObjectName("lblTitle_4")
        self.verticalLayout_5.addWidget(self.lblTitle_4)
        self._5 = QtWidgets.QHBoxLayout()
        self._5.setObjectName("_5")
        spacerItem9 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self._5.addItem(spacerItem9)
        self.btnThemSP = QtWidgets.QPushButton(parent=self.pageSanPham)
        self.btnThemSP.setObjectName("btnThemSP")
        self._5.addWidget(self.btnThemSP)
        self.btnChiTietSP = QtWidgets.QPushButton(parent=self.pageSanPham)
        self.btnChiTietSP.setObjectName("btnChiTietSP")
        self._5.addWidget(self.btnChiTietSP)
        self.btnCapNhatSP = QtWidgets.QPushButton(parent=self.pageSanPham)
        self.btnCapNhatSP.setObjectName("btnCapNhatSP")
        self._5.addWidget(self.btnCapNhatSP)
        self.btnXoaSP = QtWidgets.QPushButton(parent=self.pageSanPham)
        self.btnXoaSP.setObjectName("btnXoaSP")
        self._5.addWidget(self.btnXoaSP)
        self.btnRefreshSP = QtWidgets.QPushButton(parent=self.pageSanPham)
        self.btnRefreshSP.setObjectName("btnRefreshSP")
        self._5.addWidget(self.btnRefreshSP)
        self.verticalLayout_5.addLayout(self._5)
        self.bangSanPham = QtWidgets.QTableWidget(parent=self.pageSanPham)
        self.bangSanPham.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.bangSanPham.setAlternatingRowColors(True)
        self.bangSanPham.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.bangSanPham.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.bangSanPham.setObjectName("bangSanPham")
        self.bangSanPham.setColumnCount(8)
        self.bangSanPham.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.bangSanPham.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.bangSanPham.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.bangSanPham.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.bangSanPham.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.bangSanPham.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.bangSanPham.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.bangSanPham.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.bangSanPham.setHorizontalHeaderItem(7, item)
        self.verticalLayout_5.addWidget(self.bangSanPham)
        self.khungChuyenTrangStacked.addWidget(self.pageSanPham)
        self.pageDanhMuc = QtWidgets.QWidget()
        self.pageDanhMuc.setObjectName("pageDanhMuc")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.pageDanhMuc)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.topLayout = QtWidgets.QHBoxLayout()
        self.topLayout.setObjectName("topLayout")
        self.cbbTimKiemDM = QtWidgets.QComboBox(parent=self.pageDanhMuc)
        self.cbbTimKiemDM.setEditable(True)
        self.cbbTimKiemDM.setCurrentText("")
        self.cbbTimKiemDM.setObjectName("cbbTimKiemDM")
        self.topLayout.addWidget(self.cbbTimKiemDM)
        self.btnTimKiemDM = QtWidgets.QPushButton(parent=self.pageDanhMuc)
        self.btnTimKiemDM.setObjectName("btnTimKiemDM")
        self.topLayout.addWidget(self.btnTimKiemDM)
        self.topLayout.setStretch(0, 10)
        self.topLayout.setStretch(1, 1)
        self.verticalLayout_6.addLayout(self.topLayout)
        self.lblTitle_6 = QtWidgets.QLabel(parent=self.pageDanhMuc)
        self.lblTitle_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblTitle_6.setObjectName("lblTitle_6")
        self.verticalLayout_6.addWidget(self.lblTitle_6)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem10)
        self.btnThemDM = QtWidgets.QPushButton(parent=self.pageDanhMuc)
        self.btnThemDM.setMinimumSize(QtCore.QSize(90, 35))
        self.btnThemDM.setObjectName("btnThemDM")
        self.horizontalLayout_9.addWidget(self.btnThemDM)
        self.btnChiTietDM = QtWidgets.QPushButton(parent=self.pageDanhMuc)
        self.btnChiTietDM.setMinimumSize(QtCore.QSize(90, 35))
        self.btnChiTietDM.setObjectName("btnChiTietDM")
        self.horizontalLayout_9.addWidget(self.btnChiTietDM)
        self.btnCapNhatDM = QtWidgets.QPushButton(parent=self.pageDanhMuc)
        self.btnCapNhatDM.setMinimumSize(QtCore.QSize(90, 35))
        self.btnCapNhatDM.setObjectName("btnCapNhatDM")
        self.horizontalLayout_9.addWidget(self.btnCapNhatDM)
        self.btnXoaDM = QtWidgets.QPushButton(parent=self.pageDanhMuc)
        self.btnXoaDM.setMinimumSize(QtCore.QSize(90, 35))
        self.btnXoaDM.setObjectName("btnXoaDM")
        self.horizontalLayout_9.addWidget(self.btnXoaDM)
        self.btnRefreshDM = QtWidgets.QPushButton(parent=self.pageDanhMuc)
        self.btnRefreshDM.setObjectName("btnRefreshDM")
        self.horizontalLayout_9.addWidget(self.btnRefreshDM)
        self.verticalLayout_6.addLayout(self.horizontalLayout_9)
        self.tblDM = QtWidgets.QTableWidget(parent=self.pageDanhMuc)
        self.tblDM.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.tblDM.setAlternatingRowColors(True)
        self.tblDM.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.NoSelection)
        self.tblDM.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectItems)
        self.tblDM.setObjectName("tblDM")
        self.tblDM.setColumnCount(4)
        self.tblDM.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblDM.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblDM.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblDM.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblDM.setHorizontalHeaderItem(3, item)
        self.verticalLayout_6.addWidget(self.tblDM)
        self.khungChuyenTrangStacked.addWidget(self.pageDanhMuc)
        self.pageTonKho = QtWidgets.QWidget()
        self.pageTonKho.setObjectName("pageTonKho")
        self.verticalLayout_61 = QtWidgets.QVBoxLayout(self.pageTonKho)
        self.verticalLayout_61.setObjectName("verticalLayout_61")
        self._31 = QtWidgets.QHBoxLayout()
        self._31.setObjectName("_31")
        self.txtTimKiemTK = QtWidgets.QLineEdit(parent=self.pageTonKho)
        self.txtTimKiemTK.setObjectName("txtTimKiemTK")
        self._31.addWidget(self.txtTimKiemTK)
        self.btnTimKiemTK = QtWidgets.QPushButton(parent=self.pageTonKho)
        self.btnTimKiemTK.setObjectName("btnTimKiemTK")
        self._31.addWidget(self.btnTimKiemTK)
        self.verticalLayout_61.addLayout(self._31)
        self.lblTitle = QtWidgets.QLabel(parent=self.pageTonKho)
        self.lblTitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblTitle.setObjectName("lblTitle")
        self.verticalLayout_61.addWidget(self.lblTitle)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        self.lblTongTK = QtWidgets.QLabel(parent=self.pageTonKho)
        self.lblTongTK.setObjectName("lblTongTK")
        self.buttonLayout.addWidget(self.lblTongTK)
        spacerItem11 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.buttonLayout.addItem(spacerItem11)
        self.btnCapNhatTK = QtWidgets.QPushButton(parent=self.pageTonKho)
        self.btnCapNhatTK.setObjectName("btnCapNhatTK")
        self.buttonLayout.addWidget(self.btnCapNhatTK)
        self.btnRefreshTK = QtWidgets.QPushButton(parent=self.pageTonKho)
        self.btnRefreshTK.setObjectName("btnRefreshTK")
        self.buttonLayout.addWidget(self.btnRefreshTK)
        self.verticalLayout_61.addLayout(self.buttonLayout)
        self.tblTonKho = QtWidgets.QTableWidget(parent=self.pageTonKho)
        self.tblTonKho.setObjectName("tblTonKho")
        self.tblTonKho.setColumnCount(7)
        self.tblTonKho.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblTonKho.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblTonKho.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblTonKho.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblTonKho.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblTonKho.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblTonKho.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblTonKho.setHorizontalHeaderItem(6, item)
        self.verticalLayout_61.addWidget(self.tblTonKho)
        self.khungChuyenTrangStacked.addWidget(self.pageTonKho)
        self.pageThanhToan = QtWidgets.QWidget()
        self.pageThanhToan.setObjectName("pageThanhToan")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.pageThanhToan)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.searchLayout = QtWidgets.QHBoxLayout()
        self.searchLayout.setObjectName("searchLayout")
        self.txtTimKiemTT = QtWidgets.QLineEdit(parent=self.pageThanhToan)
        self.txtTimKiemTT.setText("")
        self.txtTimKiemTT.setObjectName("txtTimKiemTT")
        self.searchLayout.addWidget(self.txtTimKiemTT)
        self.btnTimKiemTT = QtWidgets.QPushButton(parent=self.pageThanhToan)
        self.btnTimKiemTT.setObjectName("btnTimKiemTT")
        self.searchLayout.addWidget(self.btnTimKiemTT)
        self.verticalLayout_7.addLayout(self.searchLayout)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem12)
        self.lblFromDate_2 = QtWidgets.QLabel(parent=self.pageThanhToan)
        self.lblFromDate_2.setObjectName("lblFromDate_2")
        self.horizontalLayout_10.addWidget(self.lblFromDate_2)
        self.txtTuNgayTT = QtWidgets.QDateEdit(parent=self.pageThanhToan)
        self.txtTuNgayTT.setCalendarPopup(True)
        self.txtTuNgayTT.setObjectName("txtTuNgayTT")
        self.horizontalLayout_10.addWidget(self.txtTuNgayTT)
        self.lblToDate_2 = QtWidgets.QLabel(parent=self.pageThanhToan)
        self.lblToDate_2.setObjectName("lblToDate_2")
        self.horizontalLayout_10.addWidget(self.lblToDate_2)
        self.txtDenNgayTT = QtWidgets.QDateEdit(parent=self.pageThanhToan)
        self.txtDenNgayTT.setCalendarPopup(True)
        self.txtDenNgayTT.setObjectName("txtDenNgayTT")
        self.horizontalLayout_10.addWidget(self.txtDenNgayTT)
        self.verticalLayout_7.addLayout(self.horizontalLayout_10)
        self.lblTitle_2 = QtWidgets.QLabel(parent=self.pageThanhToan)
        self.lblTitle_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblTitle_2.setObjectName("lblTitle_2")
        self.verticalLayout_7.addWidget(self.lblTitle_2)
        self.crudLayout = QtWidgets.QHBoxLayout()
        self.crudLayout.setObjectName("crudLayout")
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.crudLayout.addItem(spacerItem13)
        self.btnXacNhanTT = QtWidgets.QPushButton(parent=self.pageThanhToan)
        self.btnXacNhanTT.setObjectName("btnXacNhanTT")
        self.crudLayout.addWidget(self.btnXacNhanTT)
        self.btnXoaTT = QtWidgets.QPushButton(parent=self.pageThanhToan)
        self.btnXoaTT.setObjectName("btnXoaTT")
        self.crudLayout.addWidget(self.btnXoaTT)
        self.btnRefreshTT = QtWidgets.QPushButton(parent=self.pageThanhToan)
        self.btnRefreshTT.setObjectName("btnRefreshTT")
        self.crudLayout.addWidget(self.btnRefreshTT)
        self.verticalLayout_7.addLayout(self.crudLayout)
        self.tblThanhToan = QtWidgets.QTableWidget(parent=self.pageThanhToan)
        self.tblThanhToan.setObjectName("tblThanhToan")
        self.tblThanhToan.setColumnCount(5)
        self.tblThanhToan.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblThanhToan.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblThanhToan.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblThanhToan.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblThanhToan.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblThanhToan.setHorizontalHeaderItem(4, item)
        self.verticalLayout_7.addWidget(self.tblThanhToan)
        self.khungFrameBanner = QtWidgets.QFrame(parent=self.pageThanhToan)
        self.khungFrameBanner.setObjectName("khungFrameBanner")
        self.bannerLayout = QtWidgets.QVBoxLayout(self.khungFrameBanner)
        self.bannerLayout.setObjectName("bannerLayout")
        self.verticalLayout_7.addWidget(self.khungFrameBanner)
        self.khungChuyenTrangStacked.addWidget(self.pageThanhToan)
        self.pageVanChuyen = QtWidgets.QWidget()
        self.pageVanChuyen.setObjectName("pageVanChuyen")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.pageVanChuyen)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.grpSearch = QtWidgets.QGroupBox(parent=self.pageVanChuyen)
        self.grpSearch.setObjectName("grpSearch")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.grpSearch)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lblShipmentID = QtWidgets.QLabel(parent=self.grpSearch)
        self.lblShipmentID.setText("")
        self.lblShipmentID.setObjectName("lblShipmentID")
        self.horizontalLayout_3.addWidget(self.lblShipmentID)
        self.txtShipmentID = QtWidgets.QLineEdit(parent=self.grpSearch)
        self.txtShipmentID.setObjectName("txtShipmentID")
        self.horizontalLayout_3.addWidget(self.txtShipmentID)
        self.lblStatus = QtWidgets.QLabel(parent=self.grpSearch)
        self.lblStatus.setObjectName("lblStatus")
        self.horizontalLayout_3.addWidget(self.lblStatus)
        self.cbShipmentStatus = QtWidgets.QComboBox(parent=self.grpSearch)
        self.cbShipmentStatus.setObjectName("cbShipmentStatus")
        self.horizontalLayout_3.addWidget(self.cbShipmentStatus)
        self.lblFrom = QtWidgets.QLabel(parent=self.grpSearch)
        self.lblFrom.setObjectName("lblFrom")
        self.horizontalLayout_3.addWidget(self.lblFrom)
        self.dtFromDate = QtWidgets.QDateEdit(parent=self.grpSearch)
        self.dtFromDate.setCalendarPopup(True)
        self.dtFromDate.setObjectName("dtFromDate")
        self.horizontalLayout_3.addWidget(self.dtFromDate)
        self.lblTo = QtWidgets.QLabel(parent=self.grpSearch)
        self.lblTo.setObjectName("lblTo")
        self.horizontalLayout_3.addWidget(self.lblTo)
        self.dtToDate = QtWidgets.QDateEdit(parent=self.grpSearch)
        self.dtToDate.setCalendarPopup(True)
        self.dtToDate.setObjectName("dtToDate")
        self.horizontalLayout_3.addWidget(self.dtToDate)
        self.pushButton = QtWidgets.QPushButton(parent=self.grpSearch)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_3.addWidget(self.pushButton)
        self.verticalLayout_9.addWidget(self.grpSearch)
        self.lblTitle_7 = QtWidgets.QLabel(parent=self.pageVanChuyen)
        self.lblTitle_7.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblTitle_7.setObjectName("lblTitle_7")
        self.verticalLayout_9.addWidget(self.lblTitle_7)
        self.toolbarLayout = QtWidgets.QHBoxLayout()
        self.toolbarLayout.setObjectName("toolbarLayout")
        spacerItem14 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.toolbarLayout.addItem(spacerItem14)
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.pageVanChuyen)
        self.pushButton_3.setObjectName("pushButton_3")
        self.toolbarLayout.addWidget(self.pushButton_3)
        self.btnViewDetail = QtWidgets.QPushButton(parent=self.pageVanChuyen)
        self.btnViewDetail.setObjectName("btnViewDetail")
        self.toolbarLayout.addWidget(self.btnViewDetail)
        self.btnRefresh = QtWidgets.QPushButton(parent=self.pageVanChuyen)
        self.btnRefresh.setObjectName("btnRefresh")
        self.toolbarLayout.addWidget(self.btnRefresh)
        self.verticalLayout_9.addLayout(self.toolbarLayout)
        self.tblShipment = QtWidgets.QTableWidget(parent=self.pageVanChuyen)
        self.tblShipment.setObjectName("tblShipment")
        self.tblShipment.setColumnCount(7)
        self.tblShipment.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblShipment.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblShipment.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblShipment.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblShipment.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblShipment.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblShipment.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblShipment.setHorizontalHeaderItem(6, item)
        self.verticalLayout_9.addWidget(self.tblShipment)
        self.khungChuyenTrangStacked.addWidget(self.pageVanChuyen)
        self.pageNhanVien = QtWidgets.QWidget()
        self.pageNhanVien.setObjectName("pageNhanVien")
        self.khungChuyenTrangStacked.addWidget(self.pageNhanVien)
        self.pageBaoCao = QtWidgets.QWidget()
        self.pageBaoCao.setObjectName("pageBaoCao")
        self.khungChuyenTrangStacked.addWidget(self.pageBaoCao)
        self.pageDangXuat = QtWidgets.QWidget()
        self.pageDangXuat.setObjectName("pageDangXuat")
        self.khungChuyenTrangStacked.addWidget(self.pageDangXuat)
        self.horizontalLayout_5.addWidget(self.khungChuyenTrangStacked)
        phanTuChinhWindow.setCentralWidget(self.khungCentralwidget)
        self.phanTuMenubar = QtWidgets.QMenuBar(parent=phanTuChinhWindow)
        self.phanTuMenubar.setGeometry(QtCore.QRect(0, 0, 1015, 21))
        self.phanTuMenubar.setObjectName("phanTuMenubar")
        phanTuChinhWindow.setMenuBar(self.phanTuMenubar)
        self.phanTuStatusbar = QtWidgets.QStatusBar(parent=phanTuChinhWindow)
        self.phanTuStatusbar.setObjectName("phanTuStatusbar")
        phanTuChinhWindow.setStatusBar(self.phanTuStatusbar)

        self.retranslateUi(phanTuChinhWindow)
        self.khungChuyenTrangStacked.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(phanTuChinhWindow)

    def retranslateUi(self, phanTuChinhWindow):
        _translate = QtCore.QCoreApplication.translate
        phanTuChinhWindow.setWindowTitle(_translate("phanTuChinhWindow", "10-Tab Sidebar UI"))
        self.label_2.setText(_translate("phanTuChinhWindow", "LOGO"))
        self.label.setText(_translate("phanTuChinhWindow", "Tên doanh nghiệp"))
        self.btnTongQuan.setText(_translate("phanTuChinhWindow", "Tổng quan"))
        self.btnDonhang.setText(_translate("phanTuChinhWindow", "Đơn hàng"))
        self.btnKhachHang.setText(_translate("phanTuChinhWindow", "Khách hàng"))
        self.btnSanPham.setText(_translate("phanTuChinhWindow", "Sản phẩm"))
        self.btnDanhMuc.setText(_translate("phanTuChinhWindow", "Danh mục"))
        self.btnTonKho.setText(_translate("phanTuChinhWindow", "Tồn kho"))
        self.btnThanhToan.setText(_translate("phanTuChinhWindow", "Thanh toán"))
        self.btnVanChuyen.setText(_translate("phanTuChinhWindow", "Vận chuyển"))
        self.pushButton_2.setText(_translate("phanTuChinhWindow", "Đối Tác"))
        self.btnNhanVien.setText(_translate("phanTuChinhWindow", "Nhân viên"))
        self.btnBaoCao.setText(_translate("phanTuChinhWindow", "Báo cáo"))
        self.btnDangXuat.setText(_translate("phanTuChinhWindow", "Đăng Xuất"))
        self.nhomTimKiem2.setTitle(_translate("phanTuChinhWindow", "Tìm Kiếm"))
        self.txtTimKiemDH.setPlaceholderText(_translate("phanTuChinhWindow", "Nhập mã đơn hàng"))
        self.btnTimKiemDH.setText(_translate("phanTuChinhWindow", "Tìm kiếm"))
        self.lblFromDate.setText(_translate("phanTuChinhWindow", "Từ Ngày"))
        self.lblToDate.setText(_translate("phanTuChinhWindow", "Đến Ngày"))
        self.lblTitle_5.setStyleSheet(_translate("phanTuChinhWindow", "\n"
"font: 18pt \"Arial\";\n"
"font-weight:bold;\n"
"color:white;\n"
"background:#1976D2;\n"
"padding:15px;\n"
"border-radius:8px;\n"
"       "))
        self.lblTitle_5.setText(_translate("phanTuChinhWindow", "QUẢN LÝ ĐƠN HÀNG"))
        self.btnThemDH.setText(_translate("phanTuChinhWindow", "Thêm"))
        self.btnCapNhatDH.setText(_translate("phanTuChinhWindow", "Cập Nhật"))
        self.btnXoaDH.setText(_translate("phanTuChinhWindow", "Xóa"))
        self.btnRefreshSP_2.setText(_translate("phanTuChinhWindow", "Làm Mới"))
        item = self.tblDonHang.horizontalHeaderItem(0)
        item.setText(_translate("phanTuChinhWindow", "Mã ĐH"))
        item = self.tblDonHang.horizontalHeaderItem(1)
        item.setText(_translate("phanTuChinhWindow", "Ngày Tạo"))
        item = self.tblDonHang.horizontalHeaderItem(2)
        item.setText(_translate("phanTuChinhWindow", "Khách Hàng"))
        item = self.tblDonHang.horizontalHeaderItem(3)
        item.setText(_translate("phanTuChinhWindow", "Địa Chỉ"))
        item = self.tblDonHang.horizontalHeaderItem(4)
        item.setText(_translate("phanTuChinhWindow", "Tổng Tiền"))
        item = self.tblDonHang.horizontalHeaderItem(5)
        item.setText(_translate("phanTuChinhWindow", "Trạng Thái"))
        self.nhomTimKiem.setTitle(_translate("phanTuChinhWindow", "Tìm kiếm"))
        self.txtTimKiemKH.setPlaceholderText(_translate("phanTuChinhWindow", "Nhập tên hoặc mã số khách hàng"))
        self.btnTimKiemKH.setText(_translate("phanTuChinhWindow", "Tìm kiếm"))
        self.lblTitle_3.setStyleSheet(_translate("phanTuChinhWindow", "\n"
"font: 18pt \"Arial\";\n"
"font-weight:bold;\n"
"color:white;\n"
"background:#1976D2;\n"
"padding:15px;\n"
"border-radius:8px;\n"
"       "))
        self.lblTitle_3.setText(_translate("phanTuChinhWindow", "QUẢN LÝ KHÁCH HÀNG"))
        self.btnThemKH.setText(_translate("phanTuChinhWindow", "Thêm"))
        self.btnChiTietKH.setText(_translate("phanTuChinhWindow", "Chi tiết"))
        self.btnCapNhatKH.setText(_translate("phanTuChinhWindow", "Cập Nhật"))
        self.btnXoaKH.setText(_translate("phanTuChinhWindow", "Xóa"))
        self.btnRefreshKH.setText(_translate("phanTuChinhWindow", "Làm Mới"))
        item = self.tblKhachHang.horizontalHeaderItem(0)
        item.setText(_translate("phanTuChinhWindow", "Mã số khách hàng"))
        item = self.tblKhachHang.horizontalHeaderItem(1)
        item.setText(_translate("phanTuChinhWindow", "Tên khách hàng"))
        item = self.tblKhachHang.horizontalHeaderItem(2)
        item.setText(_translate("phanTuChinhWindow", "Kiểu khách hàng"))
        item = self.tblKhachHang.horizontalHeaderItem(3)
        item.setText(_translate("phanTuChinhWindow", "Số điện thoại"))
        self.nhomTimKiem21.setTitle(_translate("phanTuChinhWindow", "Tìm Kiếm"))
        self.btnTimKiemSP.setText(_translate("phanTuChinhWindow", "Tìm kiếm"))
        self.lblCategory.setText(_translate("phanTuChinhWindow", "Danh mục"))
        self.lblStatus_2.setText(_translate("phanTuChinhWindow", "Trạng thái"))
        self.txtTimKiemSP.setPlaceholderText(_translate("phanTuChinhWindow", "Mã hoặc tên sản phẩm..."))
        self.lblKeyword_2.setText(_translate("phanTuChinhWindow", "Từ khóa"))
        self.lblTitle_4.setStyleSheet(_translate("phanTuChinhWindow", "\n"
"font: 18pt \"Arial\";\n"
"font-weight:bold;\n"
"color:white;\n"
"background:#1976D2;\n"
"padding:15px;\n"
"border-radius:8px;\n"
"       "))
        self.lblTitle_4.setText(_translate("phanTuChinhWindow", "QUẢN LÝ SẢN PHẨM"))
        self.btnThemSP.setText(_translate("phanTuChinhWindow", "Thêm"))
        self.btnChiTietSP.setText(_translate("phanTuChinhWindow", "Chi Tiết"))
        self.btnCapNhatSP.setText(_translate("phanTuChinhWindow", "Cập nhật"))
        self.btnXoaSP.setText(_translate("phanTuChinhWindow", "Xóa"))
        self.btnRefreshSP.setText(_translate("phanTuChinhWindow", "Làm Mới"))
        item = self.bangSanPham.horizontalHeaderItem(0)
        item.setText(_translate("phanTuChinhWindow", "Mã SP"))
        item = self.bangSanPham.horizontalHeaderItem(1)
        item.setText(_translate("phanTuChinhWindow", "Tên Sản Phẩm"))
        item = self.bangSanPham.horizontalHeaderItem(2)
        item.setText(_translate("phanTuChinhWindow", "Danh Mục"))
        item = self.bangSanPham.horizontalHeaderItem(3)
        item.setText(_translate("phanTuChinhWindow", "Đơn Giá"))
        item = self.bangSanPham.horizontalHeaderItem(4)
        item.setText(_translate("phanTuChinhWindow", "Tồn Kho"))
        item = self.bangSanPham.horizontalHeaderItem(5)
        item.setText(_translate("phanTuChinhWindow", "Đơn Vị"))
        item = self.bangSanPham.horizontalHeaderItem(6)
        item.setText(_translate("phanTuChinhWindow", "Ngày Tạo"))
        item = self.bangSanPham.horizontalHeaderItem(7)
        item.setText(_translate("phanTuChinhWindow", "Trạng Thái"))
        self.btnTimKiemDM.setText(_translate("phanTuChinhWindow", "Tìm kiếm"))
        self.lblTitle_6.setStyleSheet(_translate("phanTuChinhWindow", "\n"
"font: 18pt \"Arial\";\n"
"font-weight:bold;\n"
"color:white;\n"
"background:#1976D2;\n"
"padding:15px;\n"
"border-radius:8px;\n"
"       "))
        self.lblTitle_6.setText(_translate("phanTuChinhWindow", "QUẢN LÝ DANH MỤC"))
        self.btnThemDM.setText(_translate("phanTuChinhWindow", "Thêm"))
        self.btnChiTietDM.setText(_translate("phanTuChinhWindow", "Chi tiết"))
        self.btnCapNhatDM.setText(_translate("phanTuChinhWindow", "Cập nhật"))
        self.btnXoaDM.setText(_translate("phanTuChinhWindow", "Xóa"))
        self.btnRefreshDM.setText(_translate("phanTuChinhWindow", "Làm Mới"))
        self.tblDM.setSortingEnabled(True)
        item = self.tblDM.horizontalHeaderItem(0)
        item.setText(_translate("phanTuChinhWindow", "Mã Danh Mục"))
        item = self.tblDM.horizontalHeaderItem(1)
        item.setText(_translate("phanTuChinhWindow", "Tên Danh Mục"))
        item = self.tblDM.horizontalHeaderItem(2)
        item.setText(_translate("phanTuChinhWindow", "Mô Tả"))
        item = self.tblDM.horizontalHeaderItem(3)
        item.setText(_translate("phanTuChinhWindow", "Số lượng"))
        self.txtTimKiemTK.setPlaceholderText(_translate("phanTuChinhWindow", "Tìm WarehouseID hoặc ProductID..."))
        self.btnTimKiemTK.setText(_translate("phanTuChinhWindow", "Tìm kiếm"))
        self.lblTitle.setStyleSheet(_translate("phanTuChinhWindow", "\n"
"font: 18pt \"Arial\";\n"
"font-weight:bold;\n"
"color:white;\n"
"background:#1976D2;\n"
"padding:15px;\n"
"border-radius:8px;\n"
"       "))
        self.lblTitle.setText(_translate("phanTuChinhWindow", "QUẢN LÝ KHO VÀ TỒN KHO"))
        self.lblTongTK.setText(_translate("phanTuChinhWindow", "Tổng tồn kho: 0"))
        self.btnCapNhatTK.setText(_translate("phanTuChinhWindow", "Cập Nhật"))
        self.btnRefreshTK.setText(_translate("phanTuChinhWindow", "Làm Mới"))
        item = self.tblTonKho.horizontalHeaderItem(0)
        item.setText(_translate("phanTuChinhWindow", "Mã Kho Hàng"))
        item = self.tblTonKho.horizontalHeaderItem(1)
        item.setText(_translate("phanTuChinhWindow", "Mã Sản Phẩm"))
        item = self.tblTonKho.horizontalHeaderItem(2)
        item.setText(_translate("phanTuChinhWindow", "Tên Sản Phẩm"))
        item = self.tblTonKho.horizontalHeaderItem(3)
        item.setText(_translate("phanTuChinhWindow", "Danh Mục"))
        item = self.tblTonKho.horizontalHeaderItem(4)
        item.setText(_translate("phanTuChinhWindow", "Số Lượng"))
        item = self.tblTonKho.horizontalHeaderItem(5)
        item.setText(_translate("phanTuChinhWindow", "Tồn Kho"))
        item = self.tblTonKho.horizontalHeaderItem(6)
        item.setText(_translate("phanTuChinhWindow", "Trạng Thái"))
        self.txtTimKiemTT.setPlaceholderText(_translate("phanTuChinhWindow", "Nhạp mã thanh toán"))
        self.btnTimKiemTT.setText(_translate("phanTuChinhWindow", "Tìm kiếm"))
        self.lblFromDate_2.setText(_translate("phanTuChinhWindow", "Từ Ngày"))
        self.lblToDate_2.setText(_translate("phanTuChinhWindow", "Đến Ngày"))
        self.lblTitle_2.setStyleSheet(_translate("phanTuChinhWindow", "\n"
"font: 18pt \"Arial\";\n"
"font-weight:bold;\n"
"color:white;\n"
"background:#1976D2;\n"
"padding:15px;\n"
"border-radius:8px;\n"
"       "))
        self.lblTitle_2.setText(_translate("phanTuChinhWindow", "QUẢN LÝ THANH TOÁN"))
        self.btnXacNhanTT.setText(_translate("phanTuChinhWindow", "Xác nhận đã thu tiền"))
        self.btnXoaTT.setText(_translate("phanTuChinhWindow", "Xóa Thanh Toán"))
        self.btnRefreshTT.setText(_translate("phanTuChinhWindow", "Làm Mới"))
        item = self.tblThanhToan.horizontalHeaderItem(0)
        item.setText(_translate("phanTuChinhWindow", "Mã Thanh Toán"))
        item = self.tblThanhToan.horizontalHeaderItem(1)
        item.setText(_translate("phanTuChinhWindow", "Mã Đơn Hàng"))
        item = self.tblThanhToan.horizontalHeaderItem(2)
        item.setText(_translate("phanTuChinhWindow", "Tổng Tiền"))
        item = self.tblThanhToan.horizontalHeaderItem(3)
        item.setText(_translate("phanTuChinhWindow", "Phương Thức"))
        item = self.tblThanhToan.horizontalHeaderItem(4)
        item.setText(_translate("phanTuChinhWindow", "Trạng Thái"))
        self.grpSearch.setTitle(_translate("phanTuChinhWindow", "Tìm kiếm"))
        self.txtShipmentID.setPlaceholderText(_translate("phanTuChinhWindow", "Nhập mã giao  hàng hoặc mã đơn hàng"))
        self.lblStatus.setText(_translate("phanTuChinhWindow", "Trạng thái"))
        self.lblFrom.setText(_translate("phanTuChinhWindow", "Từ ngày"))
        self.lblTo.setText(_translate("phanTuChinhWindow", "Đến ngày"))
        self.pushButton.setText(_translate("phanTuChinhWindow", "Tìm Kiếm"))
        self.lblTitle_7.setStyleSheet(_translate("phanTuChinhWindow", "\n"
"font: 18pt \"Arial\";\n"
"font-weight:bold;\n"
"color:white;\n"
"background:#1976D2;\n"
"padding:15px;\n"
"border-radius:8px;\n"
"       "))
        self.lblTitle_7.setText(_translate("phanTuChinhWindow", "QUẢN LÝ VẬN CHUYỂN"))
        self.pushButton_3.setText(_translate("phanTuChinhWindow", "Thêm"))
        self.btnViewDetail.setText(_translate("phanTuChinhWindow", "Xem Chi Tiết"))
        self.btnRefresh.setText(_translate("phanTuChinhWindow", "Làm Mới"))
        item = self.tblShipment.horizontalHeaderItem(0)
        item.setText(_translate("phanTuChinhWindow", "Mã GH"))
        item = self.tblShipment.horizontalHeaderItem(1)
        item.setText(_translate("phanTuChinhWindow", "Mã ĐH"))
        item = self.tblShipment.horizontalHeaderItem(2)
        item.setText(_translate("phanTuChinhWindow", "Khách hàng"))
        item = self.tblShipment.horizontalHeaderItem(3)
        item.setText(_translate("phanTuChinhWindow", "Đơn vị VC"))
        item = self.tblShipment.horizontalHeaderItem(4)
        item.setText(_translate("phanTuChinhWindow", "Phương thức"))
        item = self.tblShipment.horizontalHeaderItem(5)
        item.setText(_translate("phanTuChinhWindow", "Ngày giao"))
        item = self.tblShipment.horizontalHeaderItem(6)
        item.setText(_translate("phanTuChinhWindow", "Trạng thái"))


class MainWindow(QtWidgets.QMainWindow, Ui_phanTuChinhWindow):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
        self.db = Database()
        self.categories = self.db.get_categories()
        self.product_map = {}
        self.inventory_items = self.db.get_inventory_items()
        self.payment_records = self.db.get_payments()
        self.btnDanhMuc.clicked.connect(lambda: self.khungChuyenTrangStacked.setCurrentWidget(self.pageDanhMuc))
        self.btnTonKho.clicked.connect(lambda: self.khungChuyenTrangStacked.setCurrentWidget(self.pageTonKho))
        self.btnThanhToan.clicked.connect(lambda: self.khungChuyenTrangStacked.setCurrentWidget(self.pageThanhToan))
        self.setup_category_handlers()
        self.setup_inventory_handlers()
        self.setup_payment_handlers()
        self.refresh_category_table()
        self.refresh_inventory_table()
        self.refresh_payment_table()

    def setup_category_handlers(self):
        self.tblDM.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tblDM.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.cbbTimKiemDM.setEditable(True)
        self.cbbTimKiemDM.setInsertPolicy(QtWidgets.QComboBox.InsertPolicy.NoInsert)
        self.cbbTimKiemDM.lineEdit().setPlaceholderText("Nhập mã hoặc tên danh mục")
        self.btnThemDM.clicked.connect(lambda: self.open_add_category())
        self.btnChiTietDM.clicked.connect(lambda: self.open_detail_category())
        self.btnCapNhatDM.clicked.connect(lambda: self.open_update_category())
        self.btnXoaDM.clicked.connect(lambda: self.delete_selected_category())
        self.btnRefreshDM.clicked.connect(lambda: self.refresh_category_table())
        self.btnTimKiemDM.clicked.connect(lambda: self.filter_category_table())
        self.cbbTimKiemDM.currentTextChanged.connect(lambda: self.filter_category_table())

    def setup_inventory_handlers(self):
        self.tblTonKho.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tblTonKho.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.txtTimKiemTK.setPlaceholderText("Nhập mã hoặc tên sản phẩm")
        self.btnChiTietTK = QtWidgets.QPushButton("Chi tiết", parent=self.pageTonKho)
        self.buttonLayout.insertWidget(1, self.btnChiTietTK)
        self.tblTonKho.itemDoubleClicked.connect(lambda item: self.open_inventory_detail())
        self.btnChiTietTK.clicked.connect(lambda: self.open_inventory_detail())
        self.btnCapNhatTK.clicked.connect(lambda: self.open_inventory_update())
        self.btnRefreshTK.clicked.connect(lambda: self.refresh_inventory_table())
        self.btnTimKiemTK.clicked.connect(lambda: self.filter_inventory_table())
        self.txtTimKiemTK.textChanged.connect(lambda: self.filter_inventory_table())

    def setup_payment_handlers(self):
        self.tblThanhToan.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tblThanhToan.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.btnChiTietTT = QtWidgets.QPushButton("Chi tiết", parent=self.pageThanhToan)
        self.crudLayout.insertWidget(1, self.btnChiTietTT)
        self.tblThanhToan.itemDoubleClicked.connect(lambda item: self.open_payment_detail())
        self.btnChiTietTT.clicked.connect(lambda: self.open_payment_detail())
        self.btnXacNhanTT.clicked.connect(lambda: self.open_payment_detail())
        self.btnXoaTT.clicked.connect(lambda: self.delete_selected_payment())
        self.btnRefreshTT.clicked.connect(lambda: self.refresh_payment_table())
        self.btnTimKiemTT.clicked.connect(lambda: self.filter_payment_table())
        self.txtTimKiemTT.textChanged.connect(lambda: self.filter_payment_table())
        self.txtTuNgayTT.setDate(QtCore.QDate(2000, 1, 1))
        self.txtDenNgayTT.setDate(QtCore.QDate(2000, 1, 1))
        self.txtTuNgayTT.dateChanged.connect(lambda: self.filter_payment_table())
        self.txtDenNgayTT.dateChanged.connect(lambda: self.filter_payment_table())

    def generate_category_code(self):
        numbers = []
        for item in self.categories:
            code = item.get("maDM", "")
            if code.startswith("DM"):
                suffix = code[2:]
                if suffix.isdigit():
                    numbers.append(int(suffix))
        next_number = max(numbers, default=0) + 1
        return f"DM{next_number:03d}"

    def refresh_product_map(self):
        self.product_map = {}
        for item in self.inventory_items:
            category_name = item.get("danhMuc", "")
            self.product_map.setdefault(category_name, []).append(item)

    def refresh_category_table(self):
        self.categories = self.db.get_categories()
        current_text = self.cbbTimKiemDM.currentText()
        self.cbbTimKiemDM.blockSignals(True)
        self.cbbTimKiemDM.clear()
        self.cbbTimKiemDM.addItem("")
        for item in self.categories:
            self.cbbTimKiemDM.addItem(item.get("maDM", ""))
            self.cbbTimKiemDM.addItem(item.get("tenDM", ""))
        self.cbbTimKiemDM.setCurrentText(current_text)
        self.cbbTimKiemDM.blockSignals(False)
        self.populate_category_table(self.categories)

    def populate_category_table(self, items):
        self.tblDM.setRowCount(0)
        for item in items:
            row = self.tblDM.rowCount()
            self.tblDM.insertRow(row)
            self.tblDM.setItem(row, 0, QtWidgets.QTableWidgetItem(item.get("maDM", "")))
            self.tblDM.setItem(row, 1, QtWidgets.QTableWidgetItem(item.get("tenDM", "")))
            self.tblDM.setItem(row, 2, QtWidgets.QTableWidgetItem(item.get("moTa", "")))
            self.tblDM.setItem(row, 3, QtWidgets.QTableWidgetItem(str(item.get("sl", 0))))

    def filter_category_table(self):
        keyword = self.cbbTimKiemDM.currentText().strip().lower()
        if not keyword:
            self.populate_category_table(self.categories)
            return
        filtered = [
            item for item in self.categories
            if keyword in item.get("maDM", "").lower() or keyword in item.get("tenDM", "").lower()
        ]
        self.populate_category_table(filtered)

    def get_selected_category(self):
        row = self.tblDM.currentRow()
        if row < 0:
            return None
        category_id = self.tblDM.item(row, 0).text()
        for item in self.categories:
            if item.get("maDM") == category_id:
                return item
        return None

    def open_add_category(self):
        dialog = CategoryAddDialog(self)
        dialog.prepare_for_add()
        dialog.setWindowTitle("Thêm danh mục")
        if dialog.exec() == QtWidgets.QDialog.DialogCode.Accepted:
            data = dialog.get_data()
            if data["tenDM"]:
                data["maDM"] = self.generate_category_code()
                self.db.add_category(data)
                self.refresh_category_table()
                QtWidgets.QMessageBox.information(self, "Thông báo", "Thêm danh mục thành công!")

    def open_detail_category(self):
        category = self.get_selected_category()
        if category is None:
            QtWidgets.QMessageBox.warning(self, "Thông báo", "Vui lòng chọn một danh mục để xem chi tiết.")
            return
        dialog = CategoryDetailDialog(self)
        dialog.fill_category(category, self.inventory_items)
        dialog.setWindowTitle("Chi tiết danh mục")
        dialog.exec()

    def open_update_category(self, category=None):
        if category is None:
            category = self.get_selected_category()
        if category is None:
            QtWidgets.QMessageBox.warning(self, "Thông báo", "Vui lòng chọn một danh mục để cập nhật.")
            return
        dialog = CategoryAddDialog(self)
        dialog.setWindowTitle("Cập nhật danh mục")
        dialog.prepare_for_update(category)
        if dialog.exec() == QtWidgets.QDialog.DialogCode.Accepted:
            data = dialog.get_data()
            updated = {
                "maDM": category.get("maDM"),
                "tenDM": data["tenDM"],
                "moTa": data["moTa"],
                "sl": data["sl"],
            }
            self.db.update_category(updated)
            self.refresh_category_table()
            QtWidgets.QMessageBox.information(self, "Thông báo", "Cập nhật danh mục thành công!")

    def delete_category(self, category=None):
        if category is None:
            category = self.get_selected_category()
        if category is None:
            QtWidgets.QMessageBox.warning(self, "Thông báo", "Vui lòng chọn một danh mục để xóa.")
            return False
        reply = QtWidgets.QMessageBox.question(
            self,
            "Xác nhận xóa",
            f"Bạn có chắc chắn muốn xóa danh mục {category.get('maDM', '')} - {category.get('tenDM', '')}?",
            QtWidgets.QMessageBox.StandardButton.Yes | QtWidgets.QMessageBox.StandardButton.No,
        )
        if reply == QtWidgets.QMessageBox.StandardButton.Yes:
            self.db.delete_category(category.get("maDM", ""))
            self.refresh_category_table()
            self.refresh_inventory_table()
            QtWidgets.QMessageBox.information(self, "Thông báo", "Xóa danh mục thành công!")
            return True
        return False

    def delete_selected_category(self):
        self.delete_category()

    def update_inventory_total_label(self):
        total = sum(int(item.get("tonKho", 0)) for item in self.inventory_items)
        self.lblTongTK.setText(f"Tổng tồn kho: {total}")

    def populate_inventory_table(self, items):
        self.tblTonKho.setRowCount(0)
        for item in items:
            row = self.tblTonKho.rowCount()
            self.tblTonKho.insertRow(row)
            self.tblTonKho.setItem(row, 0, QtWidgets.QTableWidgetItem(item.get("maSP", "")))
            self.tblTonKho.setItem(row, 1, QtWidgets.QTableWidgetItem(item.get("tenSP", "")))
            self.tblTonKho.setItem(row, 2, QtWidgets.QTableWidgetItem(item.get("danhMuc", "")))
            self.tblTonKho.setItem(row, 3, QtWidgets.QTableWidgetItem(item.get("donViTinh", "")))
            self.tblTonKho.setItem(row, 4, QtWidgets.QTableWidgetItem(str(item.get("tonKho", 0))))
            self.tblTonKho.setItem(row, 5, QtWidgets.QTableWidgetItem(item.get("trangThai", "")))
            self.tblTonKho.setItem(row, 6, QtWidgets.QTableWidgetItem(item.get("capNhatGanNhat", "")))

    def refresh_inventory_table(self):
        self.inventory_items = self.db.get_inventory_items()
        self.refresh_product_map()
        self.populate_inventory_table(self.inventory_items)
        self.update_inventory_total_label()

    def get_selected_inventory_item(self):
        row = self.tblTonKho.currentRow()
        if row < 0:
            return None
        code = self.tblTonKho.item(row, 0).text()
        for item in self.inventory_items:
            if item.get("maSP") == code:
                return item
        return None

    def filter_inventory_table(self):
        keyword = self.txtTimKiemTK.text().strip().lower()
        if not keyword:
            self.populate_inventory_table(self.inventory_items)
        else:
            filtered = [
                item for item in self.inventory_items
                if keyword in item.get("maSP", "").lower() or keyword in item.get("tenSP", "").lower() or keyword in item.get("danhMuc", "").lower()
            ]
            self.populate_inventory_table(filtered)
        self.update_inventory_total_label()

    def open_inventory_detail(self, item=None):
        if item is None:
            item = self.get_selected_inventory_item()
        if item is None:
            QtWidgets.QMessageBox.warning(self, "Thông báo", "Vui lòng chọn một sản phẩm để xem chi tiết.")
            return
        dialog = InventoryDetailDialog(self)
        dialog.fill_item(item)
        dialog.setWindowTitle("Chi tiết tồn kho")
        dialog.exec()

    def open_inventory_update(self, item=None):
        if item is None:
            item = self.get_selected_inventory_item()
        if item is None:
            QtWidgets.QMessageBox.warning(self, "Thông báo", "Vui lòng chọn một sản phẩm để cập nhật tồn kho.")
            return
        dialog = InventoryUpdateDialog(self)
        dialog.prepare_for_update(item)
        dialog.setWindowTitle("Cập nhật tồn kho")
        dialog.exec()

    def apply_inventory_adjustment(self, item, mode, quantity, note):
        current = int(item.get("tonKho", 0))
        if mode == "Tăng":
            item["tonKho"] = current + quantity
        else:
            item["tonKho"] = max(0, current - quantity)
        item["trangThai"] = "Còn hàng" if item.get("tonKho", 0) > 0 else "Hết hàng"
        item["capNhatGanNhat"] = QtCore.QDate.currentDate().toString("dd/MM/yyyy")
        self.db.update_inventory_item(item)
        self.db.add_inventory_history(item.get("maSP", ""), {
            "ngay": item["capNhatGanNhat"],
            "loai": mode,
            "soLuong": quantity,
            "nhanVien": "NV999",
            "ghiChu": note,
        })
        self.refresh_inventory_table()
        QtWidgets.QMessageBox.information(self, "Thông báo", "Cập nhật tồn kho thành công!")

    def get_selected_payment(self):
        row = self.tblThanhToan.currentRow()
        if row < 0:
            return None
        code = self.tblThanhToan.item(row, 0).text()
        for item in self.payment_records:
            if item.get("maTT") == code:
                return item
        return None

    def populate_payment_table(self, items):
        self.tblThanhToan.setRowCount(0)
        for item in items:
            row = self.tblThanhToan.rowCount()
            self.tblThanhToan.insertRow(row)
            self.tblThanhToan.setItem(row, 0, QtWidgets.QTableWidgetItem(item.get("maTT", "")))
            self.tblThanhToan.setItem(row, 1, QtWidgets.QTableWidgetItem(item.get("maDH", "")))
            self.tblThanhToan.setItem(row, 2, QtWidgets.QTableWidgetItem(f"{item.get('tongTien', 0):,}"))
            self.tblThanhToan.setItem(row, 3, QtWidgets.QTableWidgetItem(item.get("phuongThuc", "")))
            self.tblThanhToan.setItem(row, 4, QtWidgets.QTableWidgetItem(item.get("trangThai", "")))

    def refresh_payment_table(self):
        self.payment_records = self.db.get_payments()
        self.populate_payment_table(self.payment_records)

    def filter_payment_table(self):
        keyword = self.txtTimKiemTT.text().strip().lower()
        default_date = QtCore.QDate(2000, 1, 1)
        start = self.txtTuNgayTT.date()
        end = self.txtDenNgayTT.date()
        if start == default_date:
            start = None
        if end == default_date:
            end = None
        filtered = self.payment_records
        if keyword:
            filtered = [
                item for item in filtered
                if keyword in item.get("maTT", "").lower() or keyword in item.get("maDH", "").lower()
            ]
        if start is not None and end is not None:
            filtered = [
                item for item in filtered
                if item.get("ngayTT") and start <= QtCore.QDate.fromString(item.get("ngayTT", ""), "dd/MM/yyyy") <= end
            ]
        elif start is not None:
            filtered = [
                item for item in filtered
                if item.get("ngayTT") and QtCore.QDate.fromString(item.get("ngayTT", ""), "dd/MM/yyyy") >= start
            ]
        elif end is not None:
            filtered = [
                item for item in filtered
                if item.get("ngayTT") and QtCore.QDate.fromString(item.get("ngayTT", ""), "dd/MM/yyyy") <= end
            ]
        self.populate_payment_table(filtered)

    def confirm_payment(self, payment=None):
        if payment is None:
            payment = self.get_selected_payment()
        if payment is None:
            QtWidgets.QMessageBox.warning(self, "Thông báo", "Vui lòng chọn một thanh toán để xác nhận.")
            return
        payment["trangThai"] = "Đã thanh toán"
        payment["ngayTT"] = QtCore.QDate.currentDate().toString("dd/MM/yyyy")
        self.db.update_payment(payment)
        self.refresh_payment_table()
        QtWidgets.QMessageBox.information(self, "Thông báo", "Xác nhận thanh toán thành công!")

    def delete_selected_payment(self):
        payment = self.get_selected_payment()
        if payment is None:
            QtWidgets.QMessageBox.warning(self, "Thông báo", "Vui lòng chọn một thanh toán để xóa.")
            return
        reply = QtWidgets.QMessageBox.question(
            self,
            "Xác nhận xóa",
            f"Bạn có chắc chắn muốn xóa thanh toán {payment.get('maTT', '')}?",
            QtWidgets.QMessageBox.StandardButton.Yes | QtWidgets.QMessageBox.StandardButton.No,
        )
        if reply == QtWidgets.QMessageBox.StandardButton.Yes:
            self.db.delete_payment(payment.get("maTT", ""))
            self.refresh_payment_table()
            QtWidgets.QMessageBox.information(self, "Thông báo", "Xóa thanh toán thành công!")

    def open_payment_detail(self, payment=None):
        if payment is None:
            payment = self.get_selected_payment()
        if payment is None:
            QtWidgets.QMessageBox.warning(self, "Thông báo", "Vui lòng chọn một thanh toán để xem chi tiết.")
            return
        dialog = PaymentDetailDialog(self)
        dialog.fill_payment(payment)
        dialog.setWindowTitle("Chi tiết thanh toán")
        dialog.exec()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    window = MainWindow()
    window.show()
    sys.exit(app.exec())
